### ISSUE TITLE
Expose import namespaces

### ISSUE THREAD

**Issue by wjhsf** [aml-org/amf#1023]
**I'm submitting a ...**
  - [x] feature request
  - [ ] question
  - [ ] other

**What is the current behavior?**
For the RAML file below, there is currently no way to access the namespace defined by the import (`Namespaced`) by using defined properties and methods.
```raml
#%RAML 1.0
version: v1

uses:
  Namespaced: lib.raml

/endpoint:
  post:
    body:
      type: Namespaced.RequestBody
    responses:
      200:
        body:
          type: Namespaced.ResponseBody
```

**What is the expected behavior?**
The namespace is exposed in the build artifacts, so it should be also available via a defined API.

**What is the motivation/use case for changing the behavior? (for feature requests)**
The [Commerce SDK](https://github.com/SalesforceCommerceCloud/commerce-sdk) generates TypeScript type definitions from RAML type definitions. Currently, types generated only using the name of the type, because the namespace is not accessible. However, we have recently encountered a name collision caused by importing types with the same name from two different namespaces. We would like to add namespaces to our type definitions in order to avoid the collision.

For example:
```raml
uses:
  Request: request.raml
  Response: response.raml

/endpoint:
  post:
    body:
      type: Request.Body
    responses:
      200:
        body:
          type: Response.Body
```
When traversing the AMF model, we can extract the type name (`Body`), but not the namespace (`Request` or `Response`), so we cannot generate code that differentiates between the two types.

**Please tell us about your environment:**
  
  - AMF Version: 4.7.4
  - AMF Distribution: JS 
  - Operating System: macOS
  - Link to your project: [commerce-sdk](https://github.com/SalesforceCommerceCloud/commerce-sdk)

**Other information**
I created a [small repo](https://github.com/wjhsf/amf-missing-namespaces) to search an AMF model for a specific string, with the option to use only the defined API or the build artifacts as well.

**Comment by looseale** [comment]
Hi @wjhsf.
I created an story in our internal issue system to track this: https://www.mulesoft.org/jira/browse/APIMF-3233.
We will evaluate to add an annotation or a new field in the model to save this information.

All updates on this issue will be communicated through this channel (the Github issue).
Thanks!

**Comment by gutee** [comment]
Old issue. Closing.
