### ISSUE TITLE
Unable to track JSON schema (the raw value) from a payload

### ISSUE THREAD

**Issue by jarrodek** [aml-org/amf#1084]
Your issue may already be reported! Please search on Github issues before creating one.

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] question
  - [ ] other

* **What is the current behavior?**
In RAML, when including a type that is a JSON schema I am unable to read the "raw" value anymore.

* **If the current behavior is a bug, please provide the minimal steps to reproduce with AMF code. Please don't upload AMF code mixed with yours.**
Tests to reproduce the issue: https://github.com/advanced-rest-client/amf-tests

In short:
```yaml
#%RAML 1.0

/default:
  post:
    body:
      application/json:
        type: !include schema.json
```

* **What is the expected behavior?**
When reading payload schema I am able to read the raw value of the JSON schema, from the source maps.

* **What is the motivation/use case for changing the behavior? (for feature requests)**
It was working before. Now it is not.

* **Please tell us about your environment:**
  
  - AMF Version: 4.7.6
  - AMF Distribution: JS 
  - Operating System: n/a
  - Link to your project:

* **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, Gitter, etc)
I can only refer to my old code where this was working. Previously we read the `raw` value that was included into a source map of the payload's schema. Now the `raw` value can only be read from the `#references` of the ld+json model but there's no link between the payload's schema and the reference.

**Comment by tomsfernandez** [comment]
**Note to maintainers.**: this issue was reported internally. This is the internal Jira issue: https://www.mulesoft.org/jira/browse/APIMF-3311

**Comment by arielmirra** [comment]
Hi @jarrodek! This issue has been solved in the PRs attached above. when parsing the rendered jsonld, in both XML and JSON Schema, the raw value can be restored from the model. I've based my tests on one of [your provided tests](https://github.com/jarrodek/amf-tests/blob/main/test/amf-5.0.0-beta.test.js#L11).
Thank you 🙌🏽
