### ISSUE TITLE
OAuth scopes defined in OAS specification is different from ones present in amf.json and also in UI

### ISSUE THREAD

**Issue by LokeshNSF** [aml-org/amf#1213]
Your issue may already be reported! Please search on Github issues before creating one.

* **I'm submitting a ...**
  - [] bug report
  - [ ] feature request
  - [x] question
  - [ ] other

* **What is the current behavior?**
We are generating amf.json from an OAS spec and using the amf.json to render the UI using "amf-client-js" version "4.7.5".

Here we are facing an issue related to OAuth scopes which are displayed incorrectly for an endpoint in an OAS specification.
We have an API endpoint /1/threads/edit-document with a set of OAuth scopes defined as shown below,
........
 securitySchemes:
   OAuth2:
     scopes:
            USER_MANAGE: ''
            USER_READ: ''
            USER_WRITE: ''
........
/1/threads/edit-document:
    post:
      security:
      - OAuth2:
        - USER_READ
        - USER_WRITE
where the endpoint /1/threads/edit-document has only USER_READ and USER_WRITE as defined scopes.

In the UI, when the /1/threads/edit-document endpoint is rendered using api-endpoint-documentation component, there is a security section, which incorrectly shows the following 3 different scopes for this endpoint,
USER_MANAGE, USER_READ and USER_WRITE

On debugging further, I checked the generated amf.json for this particular endpoint /1/threads/edit-document and I see that the "http://a.ml/vocabularies/security#scope" array for this endpoint has 3 objects for "USER_MANAGE", "USER_READ" and "USER_WRITE".
* **If the current behavior is a bug, please provide the minimal steps to reproduce with AMF code. Please don't upload AMF code mixed with yours.**
The generated scopes "USER_MANAGE, USER_READ and USER_WRITE" are different from what is defined for /edit-document endpoint in the OAS spec which are, "USER_READ, USER_WRITE"

* **What is the expected behavior?**
The generated scopes in amf.json as well as in the UI should be same as "USER_READ, USER_WRITE" as it is present in OAS specification.

* **What is the motivation/use case for changing the behavior? (for feature requests)**
Inconsistency in UI, where the displayed scopes are different from what is present in OAS specification.

* **Please tell us about your environment:**
  
  - AMF Version: 4.7.5
  - AMF Distribution: JS 
  - Operating System: Linux, Mac
  - Link to your project:

* **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, Gitter, etc)
Attaching a screenshot from Mulesoft's design center for reference
<img width="1495" alt="Screenshot 2021-11-26 at 1 31 15 PM" src="https://user-images.githubusercontent.com/70501713/143547156-bfeb3446-bfed-40ce-9771-06bfb222de6c.png">

**Comment by AgustinBettati** [comment]
Hello @LokeshNSF!

AMF is generating a correct model, but it appears that the API Console is obtaining the scope values from an incorrect place.

To gain more understanding of the underlying model you can take a look at https://github.com/aml-org/amf/blob/develop/documentation/model.md#parametrizedsecurityscheme (which is stored within the Operation node). Here there are 2 fields, ```scheme``` which stores the referenced security scheme (OAuth2 in your example) with all of its scopes defined, and ```settings``` which stores the values applied to this particular operation (here you will find only two scope definitions).

I am closing this issue but will notify the api console team so they can look into this.

**Comment by LokeshNSF** [comment]
Thanks @AgustinBettati for looking into this issue.
Will there be a different issue created for the API console team, just wanted to track this issue as we have a user who is waiting for this fix.
