### ISSUE TITLE
`withTags` is not available from WebAPI in Java

### ISSUE THREAD

**Issue by ShauniArima** [aml-org/amf#1230]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] question
  - [ ] other

* **What is the current behavior?**

The `withTags` function is not accessible from WepApi object.

* **If the current behavior is a bug, please provide the minimal steps to reproduce with AMF code. Please don't upload AMF code mixed with yours.**

Try building a fresh new `WepApi` object. The method is not defined.

```java
public class Main {
    public static void main() {
        WebApi api = new WebApi().withTags(List.of());
    }
}
```

* **What is the expected behavior?**

The method should be accessible from java.

* **Please tell us about your environment:**
  
  - AMF Version: 5.0.1
  - AMF Distribution: JVM  
  - Operating System: Windows 10
  - Link to your project: --

**Comment by AgustinBettati** [comment]
Hello @ShauniArima, thanks for bringing this up. 
Internal issue to track this: https://www.mulesoft.org/jira/browse/APIMF-3592.

Will let you know when this fix is merged and the release in which it will be included.

**Comment by AgustinBettati** [comment]
This fix will be available in the coming AMF release scheduled for the 10th of January. In the meantime you can use the snapshot version ```5.1.0-SNAPSHOT``` which already includes the fix, but use this version with caution as it may be unstable.

**Comment by ShauniArima** [comment]
Thank you! 🎉
