### ISSUE TITLE
Trying to parse and map a particular Open API spec crashes the APP due to memory 

### ISSUE THREAD

**Issue by anandsgar-sap** [aml-org/amf#1236]
* **I'm submitting a ..Question**
  - [ ] bug report
  - [ ] question 

* **What is the current behavior?**
* The application crashes when i execute this piece of code:
  I am using this version -->    "amf-client-js": "^4.7.7",
 

>      const amfClient = require("amf-client-js");
>      amfClient.AMF.init();
>      const amfParser = new amfClient.Oas30Parser();
>      let jsonString = JSON.stringify(require("./openapispec.json"))
>     amfParser.parseStringAsync(jsonString)
>         .then((parsedDoc) => {
>             const amfResolver = new amfClient.Oas30Resolver();
>             const resolvedModel = amfResolver.resolve(parsedDoc);
>             const webApi = resolvedModel.encodes;
>             webApi.endPoints.forEach((endPoint) => {
>                 endPoint.operations.forEach((currOperation) => {
>                     currOperation.responses[0].payloads[0].schema.toJsonSchema();
>                 });
>             });
>         })
>         .catch((err) => {
>             logger.error("Error occurred in parsing Open Api.");
>             throw err;
>         });

>  [openapispec.json.txt](https://github.com/aml-org/amf/files/7712462/openapispec.json.txt) is the file used as openAPi spec (just remove .txt  )

* **What is the expected behavior?**
          *   Wanted the JSON schema output as string .
          * Primarily we want to get the request and  response object for each Api endpoint from the openAPI spec. (could you please suggest a better/ simpler way for the same ? )

* **Please tell us about your environment:**

  - Nodejs - v12.20.1 
  - AMF Version: - 4.7.7
  - AMF Distribution: - JS
  - Operating System: - MAC/ Linux / windows (fails for all)

**Comment by tomsfernandez** [comment]
Hi @anandsgar-sap. Can you post the error here please?

**Comment by anandsgar-sap** [comment]
> Hi @anandsgar-sap. Can you post the error here please?

[74480:0x108008000] 2549481 ms: Mark-sweep 8187.6 (8208.3) -> 8187.6 (8208.3) MB, 6236.3 / 0.1 ms (average mu = 0.032, current mu = 0.000) last resort GC in old space requested

3: 0x1000a5b8f node::OnFatalError(char const*, char const*) 
4: 0x1001ee4c7 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool)
5: 0x1001ee467 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool)
6: 0x100385005 v8::internal::Heap::FatalProcessOutOfMemory(char const*)
7: 0x10038685a v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector)
: 0x10038685a v8::internal::Heap::RecomputeLimit


Also **@tomsfernandez** if you could try executing the script that I have added you would should see the same crash.

**Comment by tomsfernandez** [comment]
can you post the api spec you are using please?

**Comment by tomsfernandez** [comment]
sorry just saw the link

**Comment by tomsfernandez** [comment]
AMF is running out of memory when emitting the json schema. The "components" section in the API is pretty big so i'd suggest giving the node process more memory.

The most probable cause of the memory consumption is the emission type. The default json schema emission in AMF 4 is an "expanded emission" (we don't use refs). There is a render option to use "flattened emission" (that uses references) BUT I don't recall it being available in the `toJsonSchema` interface.

I suggest bumping to AMF 5 where the `flattened emission` is the default emission and the other one is deprecated.

This snippet works fine:

```javascript
const {JsonSchemaShapeRenderer} = require("amf-client-js");
const {OASConfiguration} = require("amf-client-js");
const client = OASConfiguration.OAS30().baseUnitClient();
client.parseDocument("file://api.json")
    .then(parsed => {
        const transformed = client.transform(parsed.baseUnit).baseUnit
        const webApi = transformed.encodes;
        webApi.endPoints.forEach((endPoint) => {
            endPoint.operations.forEach((currOperation) => {
                let shape = currOperation.responses[0].payloads[0].schema;
                const json = JsonSchemaShapeRenderer.toJsonSchema(shape, OASConfiguration.OAS30())
                console.log(json)
            });
        });
    }).catch(e => {
    console.error(e)
    })
```

**Comment by anandsgar-sap** [comment]
Thanks @tomsfernandez

Also as you see we are trying to extract the set of Input and output properties schema, is there any other method that we could use instead of _toJsonSchema()_ to achieve the same. Even if that take to loop through the list of properties

**Comment by tomsfernandez** [comment]
can you expand a bit more on that? I don't understand what you want to do

**Comment by tomsfernandez** [comment]
AMF 4 examples with compacted emission:

```javascript
// 4.7.7
console.log("STARTING")
const amfClient = require("amf-client-js");
amfClient.AMF.init();
console.log("INIT FUTURE")
const amfParser = new amfClient.Oas30Parser();
let jsonString = JSON.stringify(require("./api.json"))
amfParser.parseStringAsync(jsonString)
    .then((parsedDoc) => {
        console.log("STARTED")
        const amfResolver = new amfClient.Oas30Resolver();
        const resolvedModel = amfResolver.resolve(parsedDoc);
        const webApi = resolvedModel.encodes;
        webApi.endPoints.forEach((endPoint) => {
            endPoint.operations.forEach((currOperation) => {
                console.log("TO JSON SCHEMA")
                const options = new amfClient.render.ShapeRenderOptions().withCompactedEmission
                const json = currOperation.responses[0].payloads[0].schema.buildJsonSchema(options);
                console.log(json)
            });
        });
    })
    .catch((err) => {
        logger.error("Error occurred in parsing Open Api.");
        throw err;
    });

```

**Comment by anandsgar-sap** [comment]
> can you expand a bit more on that? I don't understand what you want to do

Yeah sure,
We want to read all the OPEN API spec, end-points and map to a corresponding structure on our side. hence we need to get the Response and input JSON Schema for each endpoint (would you recommend use to go this way, by using **buildJsonSchema**  or do you suggest a better alternative?


`Also, how do you suggest we update the reference that would be left due to "flattened emission" by buildJsonSchema, since we need to do that ?`

**Comment by tomsfernandez** [comment]
1. That method is fine
2. Refs are "self-contained" you shouldn't get a $ref pointing outside of the schema string the method returns

**Comment by tomsfernandez** [comment]
I'm closing this issue. Please feel free to keep asking if you need to.

**Comment by anandsgar-sap** [comment]
Sure I would validate a few points around this and would get back to you.
@tomsfernandez: Just wanted to know If there is any concrete example which I could follow for mapping open Api schema to a certain JSON Schema of my interest?
