### ISSUE TITLE
Method to retrieve payload schema in json format

### ISSUE THREAD

**Issue by mkmishra89** [aml-org/amf#1258]
Hi Team,

I am using AMF 5.0.1 for my development and try to implement same feature but not getting any option.

payload.schema.toJsonSchema() 

could you please suggest  the appropriate solution in AMF 5.0.1

**Comment by manisharma07** [comment]
we wanted to retrieve payload schema in json format. from the parsed doc. Can you guide us to the correct method with sample code

**Comment by AgustinBettati** [comment]
Hello @mkmishra89 @manisharma07.

Json schema rendering can be found under the `AMFElementClient`. Here is an example in [java](https://github.com/aml-org/examples/blob/master/AMF5/src/test/ts/shape.serialization.spec.ts), but you can also find examples for typescript and scala in the same repository. 
You can rely on the examples repository to help you out with the migration, as well as the [documentation](https://a.ml/docs/amf/migration_guide).
