### ISSUE TITLE
commons-io used but not declared as dependency

### ISSUE THREAD

**Issue by vromero** [aml-org/amf#126]
https://github.com/mulesoft/amf/blob/1e0f7d9ad9889b7830edc850cc5282ee8ddba167/amf-validation/jvm/src/main/scala/amf/plugins/features/validation/SHACLValidator.scala#L7

Won't work in client applications unless `commons-io` is manually included.

**Comment by gutee** [comment]
It is a dependency of org.topbraid:shacl, I don't see why it would not be included automatically
