### ISSUE TITLE
How to retain include structure when serialising parsed RAML

### ISSUE THREAD

**Issue by jgsuess** [aml-org/amf#1280]
Your issue may already be reported! Please search on Github issues before creating one.

* **I'm submitting a ...**
  - [x] question

* **What is the current behavior?**
When I parse a RAML document with dependent documents, I receive a memory structure that includes all items. However, if I want to store the information back in the original files, they get normalised into one file!

* **What is the expected behavior?**
That there is some indication in the API as to where and how data is stored in streams and files.

* **What is the motivation/use case for changing the behavior? (for feature requests)**
I have tools that want to semantically edit data in some RAML files. I do not want them all merged together.

* **Please tell us about your environment:**
  
  - AMF Version:4
  - AMF Distribution: JVM
  - Operating System: Ubuntu 20.04
  - Link to your project: commercial

**Comment by arielmirra** [comment]
Hi @jgsuess! I want to make some clarifications about AMF behavior:
- AMF parses an API into a common [API Model](https://a.ml/docs/amf/using-amf/amf_model). 
- When the API is distributed in different files, the only difference is that the parsed `BaseUnit` now has a list in the `references` property, that lists each referenced file. And even then, this `references` is oftentimes deleted from the model in some transformation pipelines.
- AMF currently emits a single string in rendering, and there is nothing planned for multi-file rendering.

Hope this answers your question. Thanks for reaching out.

NOTE: If you're using AMF, consider upgrading to version 5 as we no longer support AMF 4. More information [here](https://a.ml/docs/amf/migration_guide).

For more information about AMF, you can visit the documentation at [a.ml/docs](https://a.ml/docs).
