### ISSUE TITLE
Not able to read global security and server details from the WebAPI model after parsing openAPi spec

### ISSUE THREAD

**Issue by anandsgar-sap** [aml-org/amf#1287]
* **I'm submitting a ...**
  - [ ] question

_**Trying to understand how could i fetch the security and server configuration from the webApi ?**_

    > const { OASConfiguration, JsonSchemaShapeRenderer } = require("amf-client-js");
    > const oas30Client = OASConfiguration.OAS30().baseUnitClient();
    > const parseResult = await oas30Client.parseContent(openApiString);
		    // for Open API 3.0 version
    > const resolvedModel = oas30Client.transform(parseResult.baseUnit).baseUnit
    > const webApi = resolvedModel.encodes;

_**Attached is the OpenAPI spec for ref.[openapispec.json.txt](https://github.com/aml-org/amf/files/7983772/openapispec.json.txt)** - basically i wish to use the server and security configuration object from the spec_
  
  - AMF Version: 5.0.3
  - AMF Distribution: JS 
  - Operating System: Any

**Comment by tomsfernandez** [comment]
Hi @anandsgar-sap. Could you post the API you are using? Thanks!

**Comment by anandsgar-sap** [comment]
> Hi @anandsgar-sap. Could you post the API you are using? Thanks!

>> yes its this one: [openapispec.json.txt](https://github.com/aml-org/amf/files/7983772/openapispec.json.txt)

**Comment by anandsgar-sap** [comment]
@tomsfernandez would appreciate a response, am i clear in my query  ? I would be more than happy to share more details

**Comment by tomsfernandez** [comment]
Hi @anandsgar-sap sorry about the tardiness. Our default transformation "normalized" servers and security. You may have to look in all the api -> endpoint -> operation tree.

If you want to be able to lookup the servers and security in their original place, you can use the "editing" pipeline which keeps API Edition info.

To do this you should use:

```js
const resolvedModel = oas30Client.transform(parseResult.baseUnit, PipelineId.Editing).baseUnit
```

**Comment by anandsgar-sap** [comment]
Ohh okay @tomsfernandez . 

1. I tried a few things like resolvedModel.encodes.security, also tried to read the schema, could not find the security object, some code sample would really help.
2. Also not very sure how to get it from the operation tree as well, could you please share a sample for that as well?

**Comment by tomsfernandez** [comment]
> I tried a few things like resolvedModel.encodes.security, also tried to read the schema, could not find the security object, some code sample would really help.

Did you do this with `PipelineId.Editing` ?

> Also not very sure how to get it from the operation tree as well, could you please share a sample for that as well?

```js

const unit = // some model that you obtained.

const endPoints = unit.encodes.endPoints
const operations = endPoints.flatMap(endpoint => endpoint.operations)

const security = operations[0].security
const security2 = endPoints[1].security
const servers = operations[0].servers
```

**Comment by anandsgar-sap** [comment]
Yeah @tomsfernandez  i used PipelineId.Editing params At least it didn't work for me for the spec that i shared in the Query.

**Comment by tomsfernandez** [comment]
HI @anandsgar-sap my mistake. It seems that the `servers` are left when using Editing pipeline besides being drilled-down BUT securities aren't left, they are just drilled-down to the operations.

For example (security):
`resolvedModel.encodes.endPoints[0].operations[0].security[0]`

For example (servers):
`resolvedModel.encodes.servers`

I'll try to figure out why the "security" doesn't follow the Editing pattern

**Comment by anandsgar-sap** [comment]
Hi @tomsfernandez i could check that we get the security object at (resolvedModel.encodes.endPoints[0].operations[0].security[0] ), but was not able to extract the appropriate JSON structure to consume. DO you have recommendation for that (Also is there a generic way to model out json out of these webAPI objects)?

**Comment by anandsgar-sap** [comment]
@tomsfernandez  Could you please help me here, please let me know if we have a way currently? It is important for me to understand as i want to go ahead with this dependency.

**Comment by tomsfernandez** [comment]
> i could check that we get the security object at (resolvedModel.encodes.endPoints[0].operations[0].security[0] ), but was not able to extract the appropriate JSON structure to consume

Can you share a gist with the code you are running ? And I'm not sure what you mean by "the appropiate JSON structure to consume", maybe add an example of what you are expecting ?

> DO you have recommendation for that (Also is there a generic way to model out json out of these webAPI objects)?

Can you give me an example of this please? Do you want to serialize the web-api structure as a plain JSON object ?

**Comment by anandsgar-sap** [comment]
Can you give me an example of this please? Do you want to serialize the web-api structure as a plain JSON object ?

> yeah that is more or less what i am trying to get

**Comment by tomsfernandez** [comment]
Hi @anandsgar-sap please open another issue for this serialization of the web-api structure as a plain JSON object.
Please answer my other question in the previous comment so we can solve this.

**Comment by tomsfernandez** [comment]
I'm marking this issue as 'stale' and closing it as more than a month has passed without a response from the issue author
