### ISSUE TITLE
Inhomogenous builder interface in `amf.client.model.domain.Operation`

### ISSUE THREAD

**Issue by jgsuess** [aml-org/amf#1303]
Your issue may already be reported! Please search on Github issues before creating one.

* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] question
  - [ ] other

* **What is the current behavior?**

The type `amf.client.model.domain.Operation` offer methods `List<Request> amf.client.model.domain.Operation.requests()` and `amf.client.model.domain.Operation.withRequest(Request)`.

* **What is the expected behavior?**

If a Class offers a *multiplicity-many* get method, it should also offer a *multiplicity-many* set method.

* **What is the motivation/use case for changing the behavior? (for feature requests)**

I need to automatically infer the pairs of setters and getters without knowing the semantic. This is a reflective load/save facility.

* **Please tell us about your environment:**
  
  - AMF Version: 4
  - AMF Distribution: JVM
  - Operating System: Linux
  - Link to your project: Commercial

* **Other information**
With homogenous naming, the relationship between methods can be automatically inferred. Ideally, there would be documentation and mechanisation on how the method names are derived. The API is too big to make reliable construction by hand feasible.

**Comment by looseale** [comment]
Hi.
Fixed with commit 4a0075e49caafde1cd202fb6f9a445828b6aef51.
This will be released with the next AMF version at 9th of March
