### ISSUE TITLE
Broken link to docs

### ISSUE THREAD

**Issue by dcrossleyau** [aml-org/amf#1306]
* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [ ] question
  - [x] other

* **What is the current behavior?**

The link to documentation, on the right-hand side of the GitHub [front page](https://github.com/aml-org/amf) is broken 404.

Also going direct is broken, e.g. https://a.ml/docs/amf/migration_guide/

It did work recently, but not now.

**Comment by looseale** [comment]
Hi.
We had a server problem, it is up and running now.
Thanks for letting us know.
