### ISSUE TITLE
Not able to mock 

### ISSUE THREAD

**Issue by mkmishra89** [aml-org/amf#1320]
i am trying to mock the below code but getting error could you please help me for that.

private BaseUnit stringContentToModel(AMFBaseUnitClient client, String specDoc) throws ExecutionException, InterruptedException {
        final AMFParseResult parseResult = client.parseContent(specDoc).get();

Error : java.util.concurrent.ExecutionException: amf.core.client.scala.exception.UnsupportedDomainForDocumentException: Cannot find any registered domain plugin for current document http://a.ml/amf/default_document

**Comment by nschejtman** [comment]
Hi @mkmishra89 ,
please make sure you follow the issue reporting template. 

Regarding your question, you can check you are obtaining  the your `AMFBaseUnitClient` from an appropriate configuration. For example, if you are parsing a RAML 1.0 spec you can use the `amf.apicontract.client.platform.RAMLConfiguration.RAML10()` method to obtain such configuration

**Comment by tomsfernandez** [comment]
I'm marking this issue as stale and closing it as more than a month has gone by without an answer from the author
