### ISSUE TITLE
how to read the server using amf for java

### ISSUE THREAD

**Issue by mkmishra89** [aml-org/amf#1340]
Hi

i am trying to read server object using AMF through java but not able to read it. Could you please let me know how i can read it.

**Comment by arielmirra** [comment]
Hi @mkmishra89! it's not clear what you're trying to do, please provide more information like code or a test with the problem. 

AMF can parse APIs in files or strings: https://a.ml/docs/amf/using-amf/amf_parsing

You can also create or modify an AMF Model in memory: https://a.ml/docs/cookbook/model_in_memory

You can find more code examples in Java in the documentation provided above. Hope that helps!

**Comment by mkmishra89** [comment]
i want to read this servers object 

![image](https://user-images.githubusercontent.com/97277843/157667583-6964eb26-a288-4e29-b7d2-c13b0404e8f6.png)

**Comment by mkmishra89** [comment]
we are using below code to fetch details.

final WebApi api = (WebApi) document.encodes();
final List<Operation> operations = api.endPoints().stream().map(EndPoint::operations).flatMap(Collection::stream).collect(Collectors.toList());
operations.forEach(operation -> {
    Server server = operation.servers().get(0);
    //todo read this server object as JSON 
});

we want to read the server object as json.

**Comment by mkmishra89** [comment]
@arielmirra please look above sample code.
