### ISSUE TITLE
Not able to read server details from the WebAPI model after parsing openAPi spec using java

### ISSUE THREAD

**Issue by mkmishra89** [aml-org/amf#1342]
we are using below code to fetch details.

final WebApi api = (WebApi) document.encodes();
final List<Operation> operations = api.endPoints().stream().map(EndPoint::operations).flatMap(Collection::stream).collect(Collectors.toList());
operations.forEach(operation -> {
    Server server = operation.servers().get(0);
    //todo read this server object as JSON 
});

we want to read the server object as json.

**Comment by mkmishra89** [comment]
Gentle Reminder

**Comment by mkmishra89** [comment]
Gentle Reminder.

**Comment by mkmishra89** [comment]
Gentle Reminder

**Comment by tomsfernandez** [comment]
Hi @mkmishra89 sorry for not answering earlier, our notifier bot suddenly stopped working. Please see: https://github.com/aml-org/examples/blob/master/AMF5/src/test/java/javaPlatform/RenderDomainElementTest.java. This shows how to render domain elements like Server to the desired spec
