### ISSUE TITLE
Duplicated schemas during conversion

### ISSUE THREAD

**Issue by ShauniArima** [aml-org/amf#1344]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] question
  - [ ] other

* **What is the current behavior?**

During conversion of a RAML file that define `schemas`, linked schemas using differents `relative paths` result in different schemas in the output.

For example:
```
- folder1
  - A.json
  - B.json (ref A.json using `./A.json`)
- folder2
  - C.json (ref A.json using `../folder1/A.json`)
```

Result in a output with duplicated A in the schemas part.

You can find a sample with a test in the linked project 😉 

* **What is the expected behavior?**

A result without duplicas of schemas.

* **Please tell us about your environment:**
  
  - AMF Version: 5.1.0-SNAPSHOT and 5.0.5
  - AMF Distribution: JVM or JS -> Same behaviour here 
  - Operating System: Windows 10
  - Link to your project: https://github.com/ShauniArima/amf-sample

* **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, Gitter, etc)

It seems that the `relative paths` are used as a source of truth somewhere to check if the schemas is already defined or not. If this is the case, it can be good to use `absolute paths` to fix this behaviour.

**Comment by tomsfernandez** [comment]
Hi @ShauniArima sorry, our notification bot stopped working all of a sudden. We are triaging this issue, we will provide updates soon.

**Comment by ShauniArima** [comment]
Thank you for answering this issue 😄

**Comment by tomsfernandez** [comment]
Hi @ShauniArima, it seems this issue is originated from the same functionality as https://github.com/aml-org/amf/issues/1338. We will investigate them together. 

Internal ticket link: https://gus.my.salesforce.com/a07EE00000sRUzYYAW

**Comment by ShauniArima** [comment]
Thank you @tomsfernandez. 😄 
I was wondering if it is possible to have some news about it in one of the two issues impacted?

**Comment by hghianni** [comment]
Hi @ShauniArima, I have looked into this issue and we decided no change will be made. For us conversion is a best effort and decisions around it are strongly based on opinions, we only guarantee that the converted file will be valid. So there are cases like these where the decisions made may be unsatisfactory for some users as result is not exactly what they expected but as I said is debatable. Feel free to re-open. Thanks!

**Comment by ShauniArima** [comment]
Hi @hghianni! 👋 
Thanks for your answer. Sorry, I was not able to answer your message sooner. 😢 
I understand your point of view about decisions. But I am not sure that avoiding doubloons is related to decisions in the software. For me, it is more related to something that is not handled correctly. Maybe I am wrong so feel free to answer me! 😄
