### ISSUE TITLE
Some threads are not stopped after transformation is done

### ISSUE THREAD

**Issue by ShauniArima** [aml-org/amf#1362]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] question
  - [ ] other

* **What is the current behavior?**

Converting RAML to OpenAPI is working great but after the work is done, some threads are not stopped.

* **If the current behavior is a bug, please provide the minimal steps to reproduce with AMF code. Please don't upload AMF code mixed with yours.**

```scala
object Converter {
  def main(args: Array[String]): Unit = {
    val ramlClient = RAMLConfiguration.RAML08().baseUnitClient
    val oasClient = OASConfiguration.OAS30().baseUnitClient

    val sourceFile = args.apply(0)

    val conversionPipeline = for {
      parseResult <- ramlClient parse sourceFile
      if parseResult.conforms
      transformResult <- Future {
        oasClient transform(parseResult.baseUnit, PipelineId.Compatibility)
      }
      renderResult <- Future {
        oasClient render(transformResult.baseUnit, "application/yaml")
      }
    } yield renderResult

    val pipeline = conversionPipeline andThen {
      case Success(renderedApi) =>
        println(renderedApi)
      case Failure(exception) =>
        logger.error(exception.getMessage)
        throw exception
    }

    Await.ready(pipeline, Duration.Inf)
  }
}
```

This program will not stop until you kill it. Some threads seems to stay unclosed.

* **What is the expected behavior?**

Threads are expected to be closed as the job seems to be done.

* **What is the motivation/use case for changing the behavior? (for feature requests)**

* **Please tell us about your environment:**
  
  - AMF Version: 5.0.5
  - AMF Distribution: JVM
  - Operating System: Windows 10
  - Link to your project: --

* **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, Gitter, etc)

**Comment by tomsfernandez** [comment]
HI @ShauniArima. This is a known issue for us in AMF and it is related to Scala rather than our product. To force the threads to stop you will have to provide an ExecutionContext to the AMFConfiguration and at the end of the process, force all of its threads to stop.

You can see an example here: https://github.com/aml-org/examples/blob/master/AMF5/src/test/scala/scalaPlatform/SchedulerTest.scala

**Comment by ShauniArima** [comment]
Oh thanks, I will check that!
