### ISSUE TITLE
AML implementation depends on internal packages of target library. Clean OSGi use not possible.

### ISSUE THREAD

**Issue by jgsuess** [aml-org/amf#1404]
Your issue may already be reported! Please search on Github issues before creating one.

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] question
  - [ ] other

* **What is the current behavior?**
`JvmShapePayloadValidator.loadSchema` has a dependency on `URIV4FormatValidator`, which is an internal class. Access to internal classes is sensibly denied in OSGi. Please write code to the interface.
```
java.lang.NoClassDefFoundError: org/everit/json/schema/internal/URIV4FormatValidator
	at amf.shapes.internal.document.apicontract.validation.remote.JvmShapePayloadValidator.loadSchema(JvmShapePayloadValidator.scala:78)
```

* **If the current behavior is a bug, please provide the minimal steps to reproduce with AMF code. Please don't upload AMF code mixed with yours.**

Bundle jsonschema with `bnd`. See that internal packages are missing. Class load will fail.

* **What is the expected behavior?**

AML is working, as classes load correctly.

* **What is the motivation/use case for changing the behavior? (for feature requests)**

Use AML/AMF in Eclipse OSGi without bundling all jars.

* **Please tell us about your environment:**
  
  - AMF Version: 5.0.8
  - AMF Distribution: JVM
  - Operating System: Ubuntu 20.04
  - Link to your project: internal

* **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, Gitter, etc)

**Comment by gutee** [comment]
Old issue. Closing, can't change the dependency.
