### ISSUE TITLE
amf.apicontract.client.platform.model.document.APIContractProcessingData.withSourceSpec(Spec) is referencing internal

### ISSUE THREAD

**Issue by jgsuess** [aml-org/amf#1411]
Your issue may already be reported! Please search on Github issues before creating one.

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] question
  - [ ] other

* **What is the current behavior?**
The API builder API for amf is not closed. It leaks at least one reference to an internal class in 
`amf.apicontract.client.platform.model.document.APIContractProcessingData.withSourceSpec(amf.core.internal.remote.Spec)`

* **If the current behavior is a bug, please provide the minimal steps to reproduce with AMF code. Please don't upload AMF code mixed with yours.**
Try to make compile the call while denying access to the internal package `amf.core.internal.remote`.

* **What is the expected behavior?**
This call should not exist, or the target type should be made public.

* **What is the motivation/use case for changing the behavior? (for feature requests)**
I am trying to crawl the API and would like to rely on a clean API design without coding exceptions.

* **Please tell us about your environment:**
  
  - AMF Version:5
  - AMF Distribution: JVM
  - Operating System: Ubuntu 20.04
  - Link to your project: Proprietary

* **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, Gitter, etc)

**Comment by arielmirra** [comment]
Hi @jgsuess! That's interesting, but I couldn't find such a reference using the Java client interface, I've tried the following (starting from line 102 in the [ModelBuilderTest in AMF examples](https://github.com/aml-org/examples/blob/master/AMF5/src/test/java/javaPlatform/ModelBuilderTest.java#L102):
```java
final Document model = new Document();
model.withEncodes(api);
final BaseUnitProcessingData processingData = model.processingData();
processingData // couldn't find a method .withSourceSpec()
```


Could you provide the code example where you found this? Thank you!

**Comment by jgsuess** [comment]
This what I see in the analysis:
![image](https://user-images.githubusercontent.com/782737/169964813-586d9e88-47e5-48ae-a1de-5c599b0b2b15.png)

**Comment by jgsuess** [comment]
You cannot see it, because you are looking at a superclass, that does not have it. Try an `instanceOf` cast.
![image](https://user-images.githubusercontent.com/782737/169965174-0448e65b-7128-4a19-972c-7bc12a3746d3.png)

**Comment by arielmirra** [comment]
You're right, I've found it and analyzed changing it, but we can't change it for backward-compatibility reasons (we can't change the method firm). Thanks for the heads-up!
