### ISSUE TITLE
Identifying Containment in AMF parse tree

### ISSUE THREAD

**Issue by jgsuess** [aml-org/amf#1428]
Your issue may already be reported! Please search on Github issues before creating one.

* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [x] question
  - [ ] other

* **What is the current behavior?**
While recursively parsing the AMF datastructure I am identifying references from several location that point to shared objects like datatypes, etc. This is expected, as these objects are the result of parsing shared definitions.

In my conceptual reflection, which is in the EMF framework, there exists a notion of composition. In order to transcribe the model correctly, I would like to know how I can programmatically identify containment references as compared to non-containment references. This would also identify the containment hierarchy of the model.

Please note that my point of interaction is the Java API model. I am not interacting with AMF. This is deliberate, as I am aiming to reuse published ready-to-use versioned artifacts.

* **If the current behavior is a bug, please provide the minimal steps to reproduce with AMF code. Please don't upload AMF code mixed with yours.**

* **What is the expected behavior?**

* **What is the motivation/use case for changing the behavior? (for feature requests)**

* **Please tell us about your environment:**
  
  - AMF Version: 5
  - AMF Distribution: JVM
  - Operating System: Unbuntu 20.04
  - Link to your project: proprietary

* **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, Gitter, etc)

**Comment by nschejtman** [comment]
Hi @jgsuess ,
let me see if I understand correctly your question. The AMF model has relationships between nodes. You are asking if there's a way to classify these relationships into containment (aggregation or composition) and non-containment in the OOP sense. Correct?

**Comment by jgsuess** [comment]
Yes, that is correct. This means that my storage will be canonical without replication. At the moment, copies will be stored, as I have to interpret every item as a copy. The denormalisation also implies that intentional reuse is elided.

**Comment by jgsuess** [comment]
I guess my question could be answered if I had a query that tells me which BaseUnit an Item belongs to and how it can be identified within that base unit using a navigation string and corresponding function. Given that the BaseUnits are containments on the top level, and hold either one or more conceptual items, these items are unique based on container BaseUnit URI and the fragment of the item defined in them.
This is incidentally also the definition that the EMF framework uses to identify a model object in a resource. EMF is the framework that I am targeting.

**Comment by nschejtman** [comment]
Got it. Unfortunately we don't have such property classification explicit in our code. There's a silver lining though. Only elements that are declarable (values from the `http://a.ml/vocabularies/document#declares` property) can be referenced by 0+ elements, so no containment. The caveat here is that in our model any element is declarable. This even differs between specs, OAS 3.0 can declare "responses" while RAML 1.0 cannot. You can classify every property checking if its value is a declaration or "inlined" for a specific BaseUnit (rather than statically).

**Comment by nschejtman** [comment]
Will close with that comment, feel free to re-open
