### ISSUE TITLE
Details on editing pipeline mode

### ISSUE THREAD

**Issue by jgsuess** [aml-org/amf#1429]
Your issue may already be reported! Please search on Github issues before creating one.

* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [x] question
  - [ ] other

* **What is the current behavior?**

I am writing a recursive marshalling. While I understand that [cycling (parsing and rendering) is not recommended](https://a.ml/docs/related-docs/amf_conversion#can-i-parse-and-render-my-api-from-a-spec-to-the-same-one), I am wondering what the alternatives to this use are. The documentation is quite vague, stating only:

> you should reconsider why you are doing it and see if the framework has the capabilities of achieving what you seek in a different, more useful way.

I am guessing that the [`Editing Pipeline`](https://a.ml/docs/amf/using-amf/amf_transformation#pipelines) maybe the right approach. But beyond the name, I cannot find any examples of use or test.

Summary: Where can I find, please

* suggestions for alternative better ways to cycle between another model representation and existing raml artefacts.
* examples of the capabilities and use cases of the Editing pipeline
n/use case for changing the behavior? (for feature requests)**

* **Please tell us about your environment:**
  
  - AMF Version: 5
  - AMF Distribution: JVM
  - Operating System: Ubuntu 20.04
  - Link to your project: proprietary

**Comment by nschejtman** [comment]
Hi @jgsuess , 
that documentation is for conversion. Say you parse a RAML API spec and want to obtain a OAS API spec from it. Not sure conversion is what you are after for marshalling but I'll explain anyways:

The AMF model is unique. After parsing you will obtain a BaseUnit close to the original spec file. If you parse a RAML spec, then the model will be RAML-ish. If you want to render an OAS file you must first transform that model using the `Compatibility` pipeline which will make the BaseUnit look like it was obtained from parsing an equivalent OAS spec. 

On the other hand, the `Editing` pipeline you transform the BaseUnit to a more "canonical" model that would be neither RAML-ish nor OAS-ish but AMF-ish

**Comment by nschejtman** [comment]
What I think you will need is to render the BaseUnit to JSON-LD, which is an RDF representation format we use to represent the AMF model. You can choose to either render the parsed BaseUnit or transform it first with the `Editing` pipeline. That's up to you.

The Editing pipeline will transform you BaseUnit into a canonical AMF BaseUnit. We don't have a precise definition of all it does (it resolves links, resolves type inheritance, applies RAML resource types and traits, etc. etc.). The best you can do is to either read [the code](https://github.com/aml-org/amf/blob/develop/amf-api-contract/shared/src/main/scala/amf/apicontract/internal/transformation/AmfEditingPipeline.scala) or try it out and check the results.

If it's the same for you, then the parse-transform with editing pipeline-render JSON-LD is our most proven workflow. Many teams use it. The parse-render JSON-LD workflow should work also, but you are more likely to encounter bugs

**Comment by nschejtman** [comment]
Will close with that comment, feel free to re-open
