### ISSUE TITLE
Character encoding happing by default in operationId

### ISSUE THREAD

**Issue by mkmishra89** [aml-org/amf#1450]
Your issue may already be reported! Please search on Github issues before creating one.

* **I'm submitting a ... question**
  - [ ] question
 
while trying to get operation details we are getting encoded value.

final AMFParseResult parseResult = client.parseContent(specDoc).get(); 
BaseUnit model = parseResult.baseUnit();
final Document document = (Document) amfClient.transform(model).baseUnit();
final WebApi api = (WebApi) document.encodes();

api.endPoints().forEach(endPoint ->
                endPoint.operations().forEach(currOperation -> {currOperation.id()}.

is there any way to avoid character encoding.

Actual String : A_PurchaseReqnItemText(PurchaseRequisition='{PurchaseRequisition}',PurchaseRequisitionItem='{PurchaseRequisitionItem}',DocumentText='{DocumentText}',TechnicalObjectType='{TechnicalObjectType}',Language='{Language}

Encoded String : get_A_PurchaseReqnItemText(PurchaseRequisition%3D'%7BPurchaseRequisition%7D'%2CPurchaseRequisitionItem%3D'%7BPurchaseRequisitionItem%7D'%2CDocumentText%3D'%7BDocumentText%7D'%2CTechnicalObjectType%3D'%7BTechnicalObjectType%7D'%2CLanguage%3D'%7BLanguage%7D')

**Comment by tomsfernandez** [comment]
Hi @mkmishra89. Could you please provide us the AMF version and platform (JS or JVM) you are using?

The `id()` method of AMF elements is encoded as it is a URI. You can always decode it if you need to. How did you obtain the String values that you displayed in the issue description ? Those don't look like AMF ids.

**Comment by mkmishra89** [comment]
@tomsfernandez we are using AMF 5.0.1 and platform is java (jvm). Could you please suggest how we can decode.

**Comment by mkmishra89** [comment]
@tomsfernandez any update

**Comment by tomsfernandez** [comment]
Hi @mkmishra89. Please look at the question I posted in my previous comment.

To decode the id you can use a vainilla Java option like `java.net.URLDecoder` or something like that. AMF will always output element ids as encoded URIs because that is how the framework is intended to work.
