### ISSUE TITLE
Scheme not present for server object after converting open api 2.x.x to 3.x.x

### ISSUE THREAD

**Issue by ggolchha** [aml-org/amf#1455]
* **I'm submitting a question**

* **What is the current behavior?**
Currently the scheme is missing in server object.

* **If the current behavior is a bug, please provide the minimal steps to reproduce with AMF code. Please don't upload AMF code mixed with yours.**
private final AMFBaseUnitClient amfBaseUnit20Client = OASConfiguration.OAS20().baseUnitClient();
BaseUnit oasApi = amfBaseUnit20Client.parseContent(<openApiSpecContent>).get().baseUnit();
final BaseUnit convertedOas = amfClient.transform(oasApi, PipelineId.Compatibility()).baseUnit();
final String convertedSpec = amfClient.render(convertedOas).trim();

Note : openApiSpecContent is OAS file as string

* **What is the expected behavior?**
The expected behavior would be to get completed url in server object.
For example : 
Current State :
"servers": [
                            {
                                "url": "petstore.swagger.io/api"
                            }
                        ],
Expected State : 
"servers": [
                            {
                                "url": "http://petstore.swagger.io/api"
                            }
                        ],

* **Please tell us about your environment:**
  
  - AMF Version: 5.0.1
  - AMF Distribution: JVM 
  - Operating System: Mac O
[openapispec.txt](https://github.com/aml-org/amf/files/8998131/openapispec.txt)

**Comment by ggolchha** [comment]
Hi @tomsfernandez @nschejtman @looseale 
This question is open from several weeks, can you please help me with this ?

**Comment by gutee** [comment]
It's working as expected. Closing.

**Comment by golchha007** [comment]
@gutee 
The issue is still reproducible for me.
I converted the above attached OAS and it gets converted to 3.0.0 spec but for each action the url inside servers object does not have schemes ( http or https).
[Converted_OAS.txt](https://github.com/aml-org/amf/files/10468749/Converted_OAS.txt)
