### ISSUE TITLE
Draft-2019-09 support in documentation

### ISSUE THREAD

**Issue by deiteris** [aml-org/amf#1464]
Your issue may already be reported! Please search on Github issues before creating one.

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] question
  - [ ] other

I noticed the [Json Schema Draft 2019-09 to Draft 7 Emission](https://a.ml/docs/related-docs/json_schema_draft_2019_09_to_draft_7) section in the documentation and it mentions the following:
```
...
An initial support of Draft 2019-09 is necessary to start support of OpenAPI 3.1. This support includes parsing, emission and validation. The only aspect that is not owned by AMF is validation, which is delegated to Ajv for the JS Platform and Everit for JVM.

These libraries won’t be supporting Draft 2019-09 in the short term so we need to workaround this.
...
```

Which currently isn't precise (or maybe this information is outdated). While Everit doesn't have support for Draft 2019-09, Ajv does provide support for Draft 2019-09 (and Draft-2020-12) in its recent version (https://ajv.js.org/v6-to-v8-migration.html).

**Comment by tomsfernandez** [comment]
Hi @deiteris. Thanks for the suggestion! Ajv didn't support draft 2019-09 when we wrote that article but as you said, it does now. I'll create an issue in our internal ticket system to change this. The internal ticket is: https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE000011BLLtYAO/view.

Thanks for bringing this up!
