### ISSUE TITLE
Want Null to be replaced with undefined for the nullable properties. 

### ISSUE THREAD

**Issue by nipun0212** [aml-org/amf#1490]
Your issue may already be reported! Please search on Github issues before creating one.

* **I'm submitting a ...**
  - [x] question
Want Null to be replaced with undefined for the nullable properties. 

* **What is the current behavior?**
In the current scenario for any property for which nullable is true, we get parsed model as below

    "CostCenterName":{
                  "anyOf":[
                     {
                        "type":"string",
                        "title":"Cost Center Name",
                        "maxLength":20
                     },
                     {
                        **"type":"null"**
                     }
                  ]
               },

* **What is the expected behavior?**
We want the output to have a type as undefined instead of null.("type" : "undefined")

    "CostCenterName":{
                  "anyOf":[
                     {
                        "type":"string",
                        "title":"Cost Center Name",
                        "maxLength":20
                     },
                     {
                        **"type":"undefined"**
                     }
                  ]
               },

* **Please tell us about your environment:**
  
  - AMF Version: 5
  - AMF Distribution: JVM or JS:- Both

**Comment by gutee** [comment]
The type here is not platform-specific and should be interpreted by the user of the library. Besides that, we can't make that change as it would be a change in the current behaviour of the library.
