### ISSUE TITLE
Problem with Trait and security Schema

### ISSUE THREAD

**Issue by kamilakacprzak99** [aml-org/amf#1492]
I would like to create a ruleset that will check if there is included Security Schema and traits in the raml. 
This is fragment from the raml 
 
![image](https://user-images.githubusercontent.com/82581286/179211937-b537aef9-ce32-4c76-8d08-f1bf36dfe1ce.png)

When trying to create a ruleset it works the other way around, when security schema is implemented, it throws an error. The same thing happens with traits.
 
![image](https://user-images.githubusercontent.com/82581286/179211971-4b8d53b7-578d-424c-9e24-d76fab0a028a.png)

Is there any way to reverse this situation or how to make such a checks ?

**Comment by pope1838** [comment]
Hi @kamilakacprzak99!
The rule you've wrote checks that all security schemes object must have a name set. 
In term of security schemes, the rule will check if the api contains a declared (under securitySchemes top key) and reusable security scheme but not if you are importing a security scheme fragment.
If you only need to check if there is an include to the fragment from the API, regarding the fact if it's being used or not, then you could write the rule checking if the class document contains an item at references properties that if of class type **security.SecuritySchemeFragment**, at that would be all.
For the case of traits, the targetClass should be **apiContrat.TraitFragment**.
Keep in mind that this will not check if the imported fragment is being used at some resource.
