### ISSUE TITLE
Getting open spec file invalid.

### ISSUE THREAD

**Issue by mkmishra89** [aml-org/amf#1552]
Hello Team,

We have one spec file where under security we have 

"security": [
		{
			"basicAuthentication": []
		},
		{
			"oauth2": [
				"XXXXXXXXXXXXXXXX_1",
				"XXXXXXXXXXXXXXXX_2",
				"XXXXXXXXXXXXXXXX_3",
				"XXXXXXXXXXXXXXXX_4",
				"XXXXXXXXXXXXXXXX_5",
				"XXXXXXXXXXXXXXXX_6",
				"XXXXXXXXXXXXXXXX_7"
			]
		}
	],

and under 

"components": {
		"securitySchemes": {
			"basicAuthentication": {
				"type": "http",
				"scheme": "basic"
			}
		},

and we have 
![image](https://user-images.githubusercontent.com/97277843/185932659-a377ef91-95b1-4b38-a077-56fcf657d3e1.png)

due to this we are getting invalid spec file.

But end User want to correct from our end. Could you please suggest is there any way to solve this problem from AMF level.

Like remove some tag from security or add some file under securitySchemes.

Thanks in advance.

**Comment by looseale** [comment]
Hi @mkmishra89.
We already told you in your previous issues to use the template and provide examples and code of the problem.
This issue report is incomprehensible.
