### ISSUE TITLE
RAML resource payload schemas cannot override resource-type payload schemas

### ISSUE THREAD

**Issue by brennana** [aml-org/amf#1607]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] question
  - [ ] other

* **What is the current behavior?**
When applying a resource type over a resource, operation payload schemas that are overridden in the declaration are actually merged with the existing payload schema from the resource type (if it exists). This behavior is shown via the code below:

```js
const amf = require('amf-client-js')

async function test () {
  const ramlStr = `
  #%RAML 1.0

  resourceTypes:
    resType1:
      get:
        responses:
          200:
            body:
              application/json:
                type: Type1
      post:
        responses:
          201:
            body:
              application/json:
                type: Type1

  types:
    Type1:
      type: object
      properties:
        type1prop: string
    Type2:
      type: object
      properties:
        type2prop: string
  
  /test:
    type: resType1
    get:
      responses:
        200:
          body:
            application/json:
              type: Type2
  `

  const raml10 = amf.RAMLConfiguration.RAML10().baseUnitClient()
  const parseResult = await raml10.parseContent(ramlStr)
  const resolved = raml10.transform(parseResult.baseUnit, amf.PipelineId.Cache).baseUnit
  
  const testGET = resolved.encodes.endPoints[0].operations[0],
        testPOST = resolved.encodes.endPoints[0].operations[1]
  
  console.log(testGET.responses[0].payloads[0].schema.properties.map(prop => prop.name.value()))
  console.log(testPOST.responses[0].payloads[0].schema.properties.map(prop => prop.name.value()))
}

test()
```

* **What is the expected behavior?**
In the code above, I expected the `testGET` payload schema to only contain properties from `Type2`, but instead the final schema is a merge between `Type1` (from the resource type) and `Type2` (from the declaration). The RAML specification does not seem to say that this is the appropriate behavior, given that "Every explicit node wins over the ones that are declared in a resource type or trait" ([source](https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#algorithm-of-merging-traits-and-methods)).

I realize that the type references are expanded into larger graphs, and I suppose those graphs are being merged here in this case, but it still seems counter-intuitive, and requires workarounds when the "default" shape of a resource type payload changes in certain cases in an API declaration.
* **Please tell us about your environment:**
  
  - AMF Version: 5.1.0
  - AMF Distribution: JS
  - Operating System: Linux x64

**Comment by hghianni** [comment]
Hi @brennana! After analyzing this issue we conclude that the merge algorithm is not working exactly as the spec indicates and we agree with you that Type1 should be overridden by Type 2 instead of merging. Unfortunately at the moment we cannot change this because of backwards compatibility. Thank you !
