### ISSUE TITLE
Fetch detailed error message while validating the OAS file

### ISSUE THREAD

**Issue by manisharma07** [aml-org/amf#1611]
Your issue may already be reported! Please search on Github issues before creating one.

* **I'm submitting a ...**
  - [ ] question

* **What is the current behavior?**
     When we use amf playground to parse  oas file with error, the error message is clear
     for example:"Security scheme 'OAuth2_ClientCredentials' not found in declarations."
     But when I try to fetch the same using this code 
          final AMFBaseUnitClient client = OASConfiguration.OAS30().baseUnitClient();
          final AMFParseResult parseResult = client.parse("file://src/test/resources/examples/MyExample.json").get();
          final BaseUnit model = parseResult.baseUnit();
          assertNotNull(model);
          final AMFValidationReport report = client.validate(model).get();
          System.out.println(report.results().get(0).message());

     The error message just says "Type is mandatory in a Security Scheme Object".

    Is there a method which returns output in the expected format. ?

* **What is the expected behavior?**
    I should be able to fetch the information in the same format as in the playground.
    Expected error message: Security scheme 'OAuth2_ClientCredentials' not found in declarations

* **Please tell us about your environment:**
  
  - AMF Version: 5.0.1
  - AMF Distribution: JVM
  - Operating System: Windows

**Comment by mkmishra89** [comment]
Hello Team, Any update on the above question

**Comment by mkmishra89** [comment]
Hi,

Could you please check this and do needful.

**Comment by mkmishra89** [comment]
HI team , 

Could you please look this issue.

**Comment by hghianni** [comment]
Hi @manisharma07, please provide an example API to reproduce the issue. Thank you!

**Comment by mkmishra89** [comment]
[RM_SalesOrganization.json.txt](https://github.com/aml-org/amf/files/9819563/RM_SalesOrganization.json.txt)
@hghianni  Please find the attached spec file.

**Comment by mkmishra89** [comment]
This is what we are getting from playground .

![image](https://user-images.githubusercontent.com/97277843/196666917-5f81d105-6e85-41b3-ad20-5132ec279216.png)

Same we are expecting similar response from the code.

https://amf-model-playground.herokuapp.com/

**Comment by hghianni** [comment]
Hi @mkmishra89, in the playground we only parse the API so the error `Security scheme 'OAuth2' not found in declarations` is a parsing error. In your code you are printing errors from the AMFValidationReport. You should find the same message from the playground in the AMFParseResult. Thank you!
