### ISSUE TITLE
npm package README is out of date 

### ISSUE THREAD

**Issue by rubiesonthesky** [aml-org/amf#1625]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] question
  - [ ] other

* **What is the current behavior?**

https://www.npmjs.com/package/amf-client-js README is using old syntax which does not work anymore? It's also little bit confusing because it sounds like that you need to have Scala installed for the npm package or maybe you do? :) 

Ideally that README should tell how to use this npm package.

It also contains broken links

- [amf examples repository](https://github.com/mulesoft/amf-examples)
- [read and accept the Contributors Agreement](https://api-notebook.anypoint.mulesoft.com/notebooks#380297ed0e474010ff43)
- [here](https://github.com/mulesoft/contributor-agreements/issues)

**Comment by hghianni** [comment]
Hi @rubiesonthesky, I updated the README to the latest version. Any suggestions are welcome. Thank you!
