### ISSUE TITLE
Type array is missing in the generated RAML specification

### ISSUE THREAD

**Issue by guham** [aml-org/amf#1626]
* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [x] question
  - [ ] other

* **What is the current behavior?**

Defining a new endpoint with an array schema, without specifying the shape of the items outputs `type: array`. If the shape of the items is specified, the facet `type` is missing.

I understand there is a type inference when a RAML file is parsed ([Determine Default Types](https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#determine-default-types)), but why the `type: array` is missing when the library is used to build a RAML file?

Is there an option to display the type?

The following code:
```javascript
import amf from 'amf-client-js'

async function main () {
  const api = new amf.WebApi()

  api
    .withEndPoint('/scalar_array')
    .withOperation('post')
    .withRequest()
    .withPayload()
    .withMediaType('application/json')
    .withArraySchema('schema')
    .withItems(new amf.ScalarShape().withName('items').withDataType('http://www.w3.org/2001/XMLSchema#string'))

  const document = new amf.Document().withEncodes(api)

  const client = amf.RAMLConfiguration.RAML10().baseUnitClient()

  const generated = client.render(document)

  console.log(generated)
}

main()
```

produces this output:

```raml
#%RAML 1.0
/scalar_array:
  post:
    body:
      application/json:
        items:
          type: string
```

* **What is the expected behavior?**

`type: array` is expected to be present in the output:

```raml
#%RAML 1.0
/scalar_array:
  post:
    body:
      application/json:
        type: array
        items:
          type: string
```

* **What is the motivation/use case for changing the behavior? (for feature requests)**

Documentation generators like raml2html use the `type` to correctly render the type declarations.

* **Please tell us about your environment:**
  
  - AMF Version: 5.1.0-0
  - AMF Distribution: JS 
  - Operating System: linux x64

**Comment by hghianni** [comment]
Hi @guham, this is a bug. I created an internal [issue](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE000018jdmTYAQ/view) to fix it. Thank you!

**Comment by f-schnabel** [comment]
Hi, I would like to work on this issue. Is this already picked up internally? I read the [contributing guidelines](https://github.com/aml-org/amf/blob/develop/CONTRIBUTING.md), but the link at the bottom to accept the [Contributors Agreement](https://api-notebook.anypoint.mulesoft.com/notebooks#380297ed0e474010ff43) didn't work. Do I still need to accept something or am I allowed to work on this issue?

**Comment by f-schnabel** [comment]
I found a comment from a bot in another [PR](https://github.com/aml-org/amf/pull/1285) and it linked to a [cla agreement](https://cla.salesforce.com/sign-cla?prUrl=https%3A%2F%2Fgithub.com%2Faml-org%2Famf%2Fpull%2F1285), which I accepted now.

**Comment by hghianni** [comment]
Hi @Shadow-Devil, we haven't started this issue yet. If you want to work on it you should fork the repo, solve the issue and then we will cherry-pick your commits.

**Comment by f-schnabel** [comment]
I'm a bit lost by the complexity of the project, but I maybe found something:
https://github.com/aml-org/amf/blob/de1a6dbcf92db18674983aea151c5902c1eb6705/amf-shapes/shared/src/main/scala/amf/shapes/internal/spec/raml/emitter/RamlArrayShapeEmitter.scala#L24-L28
I think this is the place, where if the `items` node is emitted, then there is no need to display the `type: array` anymore, which is added here: https://github.com/aml-org/amf/blob/de1a6dbcf92db18674983aea151c5902c1eb6705/amf-shapes/shared/src/main/scala/amf/shapes/internal/spec/raml/emitter/RamlArrayShapeEmitter.scala#L38-L39. Since this `typeEmitted` property is from the BaseClass `RamlShapeEmitter` it is probably also used for other types, like with `object` and the identifying `properties` node. So I was thinking: Should we only emit this for arrays, which would then be kinda special, or do we want to emit the `type` node always, regardless if it is identifiable without it?

**Comment by f-schnabel** [comment]
I've created two commits, one for arrays and one for objects. As said before, this issue was only about arrays, but in my opinion we should have the same behaviour for arrays and objects.
[Array fix](https://github.com/Shadow-Devil/amf/commit/893b0d9fdf5923a6c6bba0add2dc40b0339743ac)
[Object fix](https://github.com/Shadow-Devil/amf/commit/2ba11d7da99fa00cd82b6c39275da226baa210d4)

**Comment by f-schnabel** [comment]
@hghianni Should I create a PR with the changes? You said, that you would cherry-pick the commits, so I thought I shouldn't create one.

**Comment by nschejtman** [comment]
@Shadow-Devil awesome job on that PR. Just reviewed the RAML Spec and it says two contradictory things:

From [Determine Default Types](https://github.com/raml-org/raml-spec/blob/3ba244ade44c2757f2038767d88e3647543d535a/versions/raml-10/raml-10.md#determine-default-types)
> If, and only if, a type declaration contains a facet that is unique to that type, its default type is then inferred to be the only one with support for the facet being used.

From [Array Type](https://github.com/raml-org/raml-spec/blob/3ba244ade44c2757f2038767d88e3647543d535a/versions/raml-10/raml-10.md#array-type)
> Array types MUST be declared by using either the array qualifier [] at the end of a type expression or array as the value of a type facet

That said, I believe both cases are acceptable. We should make this configurable as a RenderOption in our core module so clients can decide whether to use explicit or implicit types.

@Shadow-Devil if you still are willing to work on this, these are the places you need to look at: 
* [Render options for scala clients](https://github.com/aml-org/amf-core/blob/develop/shared/src/main/scala/amf/core/client/scala/config/RenderOptions.scala) 
* [Render options for JVM and JS clients](https://github.com/aml-org/amf-core/blob/develop/shared/src/main/scala/amf/core/client/platform/config/RenderOptions.scala)

**Comment by f-schnabel** [comment]
Thank you @nschejtman! I will take a look at the RenderOptions 🙂

**Comment by f-schnabel** [comment]
@nschejtman 
What do you think should the default be?
My proposal would be to call it 
`typeInference: Boolean = false`
with a setter:
```scala
/** Don't render <pre>type</pre> facade if the type is already clear by the unique facade. */
  def withTypeInference: RenderOptions = copy(typeInference = true)
```

But maybe you there is a better name and the default should be to don't render the `type` facade.
You can also see the proposal here: https://github.com/aml-org/amf-core/commit/3c6ef51236cc700a0a5c8708f08828183800ee8b

**Comment by nschejtman** [comment]
@Shadow-Devil awesome job! Would call it `implicitRamlTypes`, _inference_ in the context of semantic graphs means something else. Also would set the default to `true` to maintain backwards compatiibility.

**Comment by f-schnabel** [comment]
@nschejtman 
I've updated the name, the default setting and created a PR. I would be happy if you could review it. 😄

**Comment by nschejtman** [comment]
@Shadow-Devil Approved 👏. Will cherry pick it so it runs on our CI pipeline

**Comment by nschejtman** [comment]
@Shadow-Devil cherry-picked PR https://github.com/aml-org/amf-core/pull/563

**Comment by nschejtman** [comment]
@Shadow-Devil your changed have been merged. Congratulations 👏
