### ISSUE TITLE
JSON schema client doesn't resolve `$ref` links correctly

### ISSUE THREAD

**Issue by deiteris** [aml-org/amf#1670]
Your issue may already be reported! Please search on Github issues before creating one.

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] question
  - [ ] other

* **What is the current behavior?**

I'm trying to build JSON schema from RAML data types and convert JSON schemas back to RAML data types. RAML client parses the content without any issues, but JSON schema client is unable to resolve `$ref` links inside definitions which leads to validation errors.

This issue does not occur when the same JSON schema is defined as RAML type and parsed with RAML client.

* **If the current behavior is a bug, please provide the minimal steps to reproduce with AMF code. Please don't upload AMF code mixed with yours.**

Given the following code:
```js
import amf from 'amf-client-js'

(async () => {
    const raml = `
#%RAML 1.0 Library

types:
    MyType:
        type: object
        properties:
            prop1: string
            prop2: integer
            prop3: LinkedType
    
    LinkedType:
        type: array
        items: string
    `

    const ramlConfig = amf.RAMLConfiguration.RAML10()
    const ramlClient = ramlConfig.baseUnitClient()

    const jsonSchemaConfig = amf.JsonSchemaConfiguration.JsonSchema()
    const jsonSchemaClient = jsonSchemaConfig.baseUnitClient()

    let result = await ramlClient.parseContent(raml)

    let validation = await ramlClient.validate(result.baseUnit)
    console.log(result.merge(validation).toString())

    const transformed = ramlClient.transform(result.baseUnit, amf.PipelineId.Editing)

    const jsonSchema = amf.JsonSchemaShapeRenderer.toJsonSchema(transformed.baseUnit.declares[0], jsonSchemaConfig)

    console.log(jsonSchema)

    result = await jsonSchemaClient.parseContent(jsonSchema)

    validation = await jsonSchemaClient.validate(result.baseUnit)
    console.log(result.merge(validation).toString())

    const ramlType = amf.RamlShapeRenderer.toRamlDatatype(result.baseUnit.declares[0], ramlConfig)
    console.log(ramlType)
})()
```

Will parse the RAML, render `MyType` as JSON schema containing a link to `LinkedType`, parse the resulting JSON schema and render RAML type from it. However, JSON Schema client shows validation error and resulting RAML data type is missing `LinkedType`.

* **What is the expected behavior?**

Link to `LinkedType` should be resolved correctly and JSON schema client shouldn't produce validation errors.

* **Please tell us about your environment:**
  
  - AMF Version: 5.1.2
  - AMF Distribution: JS 
  - Operating System: Windows 10 22H2

**Comment by hghianni** [comment]
Hi @deiteris! This was a bug, I already fixed it. It will be present in the next AMF version 5.2.3, scheduled for January 11. Thanks!
