### ISSUE TITLE
Node client: Cannot find target for parametrized resource type

### ISSUE THREAD

**Issue by jarrodek** [aml-org/amf#171]
I am trying to use resolve function to produce canonical form from the API spec. I am experiencing the following error:
```
Cannot find target for parametrized resource type file://raml-example-api/api.raml#/web-api/end-points/%2Fpeople%2F%7BpersonId%7D/
```
The API I am trying to use in my example API that I am using to work with demo applications: 
https://github.com/advanced-rest-client/raml-example-api

Let me know if you need more details.

**Comment by gutee** [comment]
Done in jira issue
