### ISSUE TITLE
Root-level annotations are lost and other are not validated correctly when loading already parsed AMF Graph

### ISSUE THREAD

**Issue by deiteris** [aml-org/amf#1743]
Your issue may already be reported! Please search on Github issues before creating one.

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] question
  - [ ] other

* **What is the current behavior?**

When parsing a RAML 1.0 document with annotations, all annotations are validated correctly and root-level validations appear in the AMF Graph correctly. But, when saved to graph and parsed again from the graph, root-level annotations are lost and type-level annotations are treated as invalid.

* **If the current behavior is a bug, please provide the minimal steps to reproduce with AMF code. Please don't upload AMF code mixed with yours.**

The following code reproduces the issue:
```js
import amf from 'amf-client-js'
import { assert } from 'console';

(async () => {
    const raml = `
#%RAML 1.0 Library

annotationTypes:
    instance: AnnotatedType
    custom_id: string
    custom_rule: object

(instance):
    id: "12344321"
    prop1: "Some value"
    prop2: 1234
    prop3: []

types:
    BaseAnnotatedType:
        type: object
        properties:
            id:
                type: string
                (custom_id): "1234"
            prop1:
                type: string
                (custom_rule):
                    rule1: "Sample text"
                    rule2: "Lorem Ipsum"

    AnnotatedType:
        type: BaseAnnotatedType
        properties:
            prop2: integer
            prop3: array
    `

    const client = amf.RAMLConfiguration.RAML10().baseUnitClient()

    const before = await client.parseContent(raml)

    const beforeValid = await client.validate(before.baseUnit)
    console.log(before.merge(beforeValid).toString())

    assert(before.baseUnit.customDomainProperties.length > 0, "No annotations found before parsing.")

    const graph = JSON.stringify(client.renderGraphToBuilder(before.baseUnit, new amf.org.yaml.builder.JsOutputBuilder()))

    const after = await client.parseContent(graph)

    const afterValid = await client.validate(after.baseUnit)
    console.log(before.merge(afterValid).toString())

    assert(after.baseUnit.customDomainProperties.length > 0, "No annotations found after parsing.")
})()
```

Will result in the following output:
```
Model: http://a.ml/amf/default_document
Conforms: true
Number of results: 0

Model: http://a.ml/amf/default_document
Conforms: false
Number of results: 2

Level: Violation

- Constraint: http://a.ml/vocabularies/amf/parser#DomainProperty-schema-minCount
  Message: type is mandatory for a RAML annotationType
  Severity: Violation
  Target: http://a.ml/amf/default_document#/declares/custom_id
  Property: http://a.ml/vocabularies/shapes#schema
  Range:
  Location:

- Constraint: http://a.ml/vocabularies/amf/parser#DomainProperty-schema-minCount
  Message: type is mandatory for a RAML annotationType
  Severity: Violation
  Target: http://a.ml/amf/default_document#/declares/custom_rule
  Property: http://a.ml/vocabularies/shapes#schema
  Range:
  Location:

Assertion failed: No annotations found after parsing.
```

* **What is the expected behavior?**

Existing type-level annotations must be validated correctly, and root-level annotations appearing when parsing RAML from AMF Graph.

* **Please tell us about your environment:**
  
  - AMF Version: 5.2.5
  - AMF Distribution: JS
  - Operating System: Windows 10 22H2

* **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, Gitter, etc)

If possible, I also would like to know whether there's any workaround for this.

**Comment by nschejtman** [comment]
Hi @deiteris , I was able to reproduce this bug. Reported a case in out [internal tracker](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001NLy0sYAD/view)

**Comment by arielmirra** [comment]
Hi @deiteris! This happens because of what [Ale said](https://github.com/aml-org/amf/issues/1750#issuecomment-1796063366) in issue #1750, validation is making changes to the BaseUnit, thus you shouldn't keep using it after validation. 

If you want the model to be resolved then use `.transform()` instead, or if you want to validate it, make a copy using `.cloneUnit()` and use that one to validate.

Hope it helps!
