### ISSUE TITLE
Query parameters model very depends on location [json/ld]

### ISSUE THREAD

**Issue by jarrodek** [aml-org/amf#177]
In HTTP method model query parameters are defined under `http://raml.org/vocabularies/http#parameter` property as an array of a type of `http://raml.org/vocabularies/http#Parameter`.

Trait's query parameters are, however, defined differently. They comes as a `http://raml.org/vocabularies/data#queryParameters` property where parameters are keys of an object and the object is of type of `http://raml.org/vocabularies/data#Object`.

This makes you create two completely different implementation of extracting essentially the same data. So the question is if there is any practical reason for query parameters to have different models representing the same information?

**Comment by gutee** [comment]
Done in jira issue
