### ISSUE TITLE
How to distinguish NilShape and AnyShape?

### ISSUE THREAD

**Issue by deiteris** [aml-org/amf#1772]
Your issue may already be reported! Please search on Github issues before creating one.

* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [x] question
  - [ ] other

I'm making custom processing with the JS library (using TS language) and I've been trying to find a way to reliably distinguish `NilShape` from `AnyShape` without any success. 

According to RAML specification, nil type is a [scalar type](https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#nil-type). However, in the AMF model, it seems to be no different than `AnyShape` (in TS typings, `NilShape` just derives from `AnyShape` without any additions) and `ScalarShape` does not include **nil** dataType (while `ScalarNode` includes it!). 

Is it some kind of inconsistency or it needs to be identified using some other means?

* **Please tell us about your environment:**
  
  - AMF Version: 5.2.6
  - AMF Distribution: JS
  - Operating System: Windows 10 22H2
  - Link to your project:

**Comment by looseale** [comment]
Hi.

I would say that the easier way is to use some instance class matching methods (instanceof, compare with getPropotype, or some other). If it is not `instanceof NilShape` it is an AnyShape.
If for some reason you cannot do that you could also use the method `.graph()` and check the `types` there. This returns a list of IRIs with the types of the DomainElement. If there is the NilShape IRI there, it is a NilShape.

The AMF Model is not an exact copy of the RAML model, so you could find differences between them.

**Comment by deiteris** [comment]
Hi looseale, 

Ah, right! Yeah, `instanceof` will work as well :) Thanks!
