### ISSUE TITLE
Windows version keeps using relative paths when parser accepts absolute path

### ISSUE THREAD

**Issue by deiteris** [aml-org/amf#1815]
Your issue may already be reported! Please search on Github issues before creating one.

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] question
  - [ ] other

* **What is the current behavior?**

When Windows parser is invoked with the absolute path to the source, the source location is absolute, but all references are relative. On Linux, both source location and all references are absolute.

* **If the current behavior is a bug, please provide the minimal steps to reproduce with AMF code. Please don't upload AMF code mixed with yours.**

data.raml
```yaml
#%RAML 1.0 Library
uses:
  base: base.raml
```

base.raml
```yaml
#%RAML 1.0 Library
```

Sample code:
```js
import amf from "amf-client-js"
import path from 'path'

(async () => {
  const client = amf.RAMLConfiguration.RAML10().baseUnitClient()

  const absPath = path.join(__dirname, 'data.raml')
  const data = await client.parse(`file://${absPath}`)

  // Windows - file://C:%5CSources%5Camf-example%5Cdata.raml
  // Linux - file:///home/user/amf-example/data.raml
  console.log(data.baseUnit.location)

  // Windows - file://base.raml
  // Linux - file:///home/user/amf-example/base.raml
  console.log(data.baseUnit.references()[0].location)
})()
```

* **What is the expected behavior?**

Path should be the same on both platforms.

* **Please tell us about your environment:**
  
  - AMF Version: 5.4.0
  - AMF Distribution: JS 
  - Operating System: Windows 10 22H2 and Ubuntu 22.04.02 LTS

**Comment by nschejtman** [comment]
Hi @deiteris 
we will need some time to setup a Windows environment to triage this issue. Will report [a ticket](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001UhlrXYAR/view) to triage this case and update this issue with the findings.

**Comment by arielmirra** [comment]
Hi @deiteris! I'm happy to announce i've haven't been able to reproduce this bug anymore, i've tried typescript and scala environments (in windows of course). 

See attached examples for details:
![WhatsApp Image 2023-11-24 at 17 52 37](https://github.com/aml-org/amf/assets/8195364/397da4c4-653c-44f8-bf86-5f84df60dc2f)
![WhatsApp Image 2023-11-24 at 17 51 31](https://github.com/aml-org/amf/assets/8195364/df0af247-1c04-4a78-ad31-204f8cf00ff5)
![WhatsApp Image 2023-11-24 at 17 42 33](https://github.com/aml-org/amf/assets/8195364/4e21da22-d86e-49ba-b701-f105f79fe3d6)

This tests all contain the same file structure described in your report. Hope this helps, thank you!
