### ISSUE TITLE
Using functionConstraint in validations

### ISSUE THREAD

**Issue by gortegasntt** [aml-org/amf#1819]
I am using #%Validation Profile 1.0 to create a custom validation rule for MuleSoft, but when I try to add the functionConstraint, it throws the following error: "Ambiguous node in union range, found 0 compatible mappings from 8 mappings".

How can I make the validation in JS and use it?

**Comment by tomsfernandez** [comment]
Hi @gortegasntt, `functionContraints` are no longer supported in Validation Profiles. Where did you see this so we can patch the documentation? I'm closing the issue for now as it no longer applies but feel free to keep on asking (just tag me in the comment)

**Comment by gortegasntt** [comment]
Hi @tomsfernandez , I found it here: https://github.com/aml-org/amf/blob/develop/documentation/validation.md#functionvalidation-node

Thanks

**Comment by gortegasntt** [comment]
Hi @tomsfernandez, where can I find documentation on how to use rego in the validations?
