### ISSUE TITLE
Trying to parse async specification file through java 

### ISSUE THREAD

**Issue by mkmishra89** [aml-org/amf#1833]
Hi Team,

We are trying to parse async specification file using java. Could you please guide us which client we can use for this.
If possible could you please share the sample java code for the same

Thanks,
Mukesh Mishra

**Comment by mkmishra89** [comment]
Hi Team,

Could you please update for above question. It is blocker for us


Thanks,
Mukesh Mishra

**Comment by arielmirra** [comment]
Hi @mkmishra89! If you're trying to parse using java, you should use the amf client, here we have a suite of examples using amf with java: https://github.com/aml-org/examples/tree/master/AMF5/src/test/java/javaPlatform

in particular, you should look into the parsing tests: https://github.com/aml-org/examples/blob/master/AMF5/src/test/java/javaPlatform/ParsingTest.java

hope those help!
