### ISSUE TITLE
Please provide the link for AMF playground

### ISSUE THREAD

**Issue by mkmishra89** [aml-org/amf#1839]
Hi Team,

Earlier we this end point for palygroud : https://amf-model-playground.herokuapp.com/.

But now it is not working. Could you please shared the link if it modified or changed.

Thanks,
Mukesh Mihsra

**Comment by mkmishra89** [comment]
Hi Team,

Gentle Reminder !!

**Comment by tomsfernandez** [comment]
Hi @mkmishra89 sorry about this. We are having a problem with heroku and the playground is currently down. We will be updating you when we have it UP again.

**Comment by mkmishra89** [comment]
Hi Tomas,


this is how we are using to parse the file.

final AMFBaseUnitClient asynchclient = AsyncAPIConfiguration.Async20().baseUnitClient();
		final BaseUnit asynchUnresolvedModel =
				asynchclient.parse("file://src/test/resources/testSchemas/reqRes/Test.json").get().baseUnit();
		final BaseUnit asynchResolvedModel = asynchclient.transform(asynchUnresolvedModel).baseUnit();
		final Document asynchDocument = (Document) asynchResolvedModel;
		AsyncApi encodes = (AsyncApi) asynchDocument.encodes();
		encodes.endPoints().forEach(endPoint -> {
			endPoint.operations().forEach(operation -> {
				System.out.println(operation.method().value());

			});
		});

==================
And another one also we tried: 

final AMFBaseUnitClient client = APIConfiguration.API().baseUnitClient();
		final AMFParseResult parseResult = client.parseContent("src/test/resources/testSchemas/reqRes/OP_ALLERGENEVENTS.json").get();
		final BaseUnit model = parseResult.baseUnit();
		final DomainElement asyncApi = ((Document) model).encodes();

**Comment by mkmishra89** [comment]
Hi Team,

Gentle Reminder !!

Thanks,
Mukesh Mishra

**Comment by golchha007** [comment]
Hi @tomsfernandez 
Is playground up for usage ?

**Comment by gutee** [comment]
Hi! The playground will not be uploaded to Heroku for the moment. If you want to use it, you can run it directly from the repo: https://github.com/aml-org/astexplorer
