### ISSUE TITLE
Not Able to read description for asyncApi

### ISSUE THREAD

**Issue by mkmishra89** [aml-org/amf#1840]
Hi Team,

we are trying to parse asyncApi but getting dificulty while reading description in seide channels. We are using JAVA as a platform.

{
    "asyncapi": "2.0.0",
    "x-sap-catalog-spec-version": "1.0",
    "info": {
        "title": "Allergen Events",
        "version": "1.0",
        "description": "An allergen is a substance that can trigger an allergic reaction. The following events are available for allergen:\r\n\r\n * Allergen changed\r\n * Allergen created\r\n * Allergen deleted"
    },
    "x-sap-api-type": "EVENT",
    "x-sap-shortText": "\r\n\r\n\r\nInforms a remote system about created, changed, and deleted allergen in an SAP S/4HANA system.",
    "x-sap-stateInfo": {
        "state": "active"
    },
    "channels": {
        "ce/sap/s4/beh/allergen/v1/Allergen/Changed/v1": {
            "subscribe": {
                "message": {
                    **"description": "This event is raised when an allergen instance is changed.",**
                    **"$ref": "#/components/messages/sap_s4_beh_allergen_v1_Allergen_Changed_v1"**
                }
            }
        },

Could you please help us with method. Even AMF playground is also not working for US.

Thanks,
Mukesh Mishra

**Comment by mkmishra89** [comment]
Hi Team,

Gentle Reminder !!

Thanks,
Mukesh Kumar Mishra

**Comment by mkmishra89** [comment]
Hi @arielmirra

Could you please look above request, it is blocker for us.

**Comment by tomsfernandez** [comment]
Hi @mkmishra89 can you share us a code block of how you are accessing the field please ? Please use the issue template as that helps us help you faster.

**Comment by mkmishra89** [comment]
Hi Tomas,

this is how we are using to parse the file.

final AMFBaseUnitClient asynchclient = AsyncAPIConfiguration.Async20().baseUnitClient();
final BaseUnit asynchUnresolvedModel =
asynchclient.parse("file://src/test/resources/testSchemas/reqRes/Test.json").get().baseUnit();
final BaseUnit asynchResolvedModel = asynchclient.transform(asynchUnresolvedModel).baseUnit();
final Document asynchDocument = (Document) asynchResolvedModel;
AsyncApi encodes = (AsyncApi) asynchDocument.encodes();
encodes.endPoints().forEach(endPoint -> {
endPoint.operations().forEach(operation -> {
System.out.println(operation.method().value());

	});
});
==================
And another one also we tried:

final AMFBaseUnitClient client = APIConfiguration.API().baseUnitClient();
final AMFParseResult parseResult = client.parseContent("src/test/resources/testSchemas/reqRes/OP_ALLERGENEVENTS.json").get();
final BaseUnit model = parseResult.baseUnit();
final DomainElement asyncApi = ((Document) model).encodes();

**Comment by mkmishra89** [comment]
Hi Team,

Gentle Reminder !!

Thanks,
Mukesh Mishra

**Comment by mkmishra89** [comment]
Hi Team,

Gentle Reminder !!

Thanks,
Mukesh Mishra

**Comment by mkmishra89** [comment]
Hi Team,

Gentle Reminder !!

Thanks,
Mukesh Mishra

**Comment by mkmishra89** [comment]
@tomsfernandez ,

Could you please look above issue. We are blocked due this.


Thanks,
Mukesh Mishra

**Comment by tomsfernandez** [comment]
Hi @mkmishra89, accessing `encodes.description` returns the description. I checked it with your code. I'm closing this issue.
