### ISSUE TITLE
Not able to find readable object for Channels,Components and payloads

### ISSUE THREAD

**Issue by mkmishra89** [aml-org/amf#1848]
Your issue may already be reported! Please search on Github issues before creating one.

* **I'm submitting a ...**
  - [ ] question

* **What is the current behavior?**

Currently we are able to get all readable object for oas file.

* **What is the expected behavior?**

We want to parse AsyncApi and need readable object for components, message,payload and header

* **What is the motivation/use case for changing the behavior? (for feature requests)**

* **Please tell us about your environment:**
  
  - AMF Version:5.x.x
  - AMF Distribution: JVM
  - Operating System:window

We are trying to parse asynApi but not able to find readable object for channels, component and payloads. Could you please help for the same. It is blocker for us.

Please find the below asyncAPI for your refrences.

{
"asyncapi": "2.0.0",
"spec-version": "1.0",
"info": {
"title": "Test",
"version": "1.0",
"description": "Test Description"
},
"x-api-type": "EVENT",
"x-shortText": "information details",
"x-stateInfo": {
"state": "active"
},
"channels": {
"ce/test/t4/test1/test2/v1/test3/Changed/v1": {
"subscribe": {
"message": {
"description": "Description.",
"$ref": "#/components/messages/test_t4_test1_test2_v1_test3_Changed_v1"
}
}
}
},
"components": {
"messages": {
"test_t4_test1_test2_v1_test3_Changed_v1": {
"name": "test_t4_test1_test2_v1_test3_Changed_v1",
"summary": "summary",
"description": "dDscription",
"headers": {
"properties": {
"type": {
"const": "test_t4_test1_test2_v1_test3_Changed_v1"
},
"source": {
"const": ""
},
"datacontenttype": {
"const": "application/json"
}
}
},
"payload": {
"$ref": "#/components/schemas/test1_t4_beh_test2_v1_test3_Changed_v1"
},
"traits": [
{
"$ref": "#/components/messageTraits/testContext"
}
]
}
},
"schemas": {
"test1_t4_beh_test2_v1_test3_Changed_v1": {
"type": "object",
"properties": {
"AllergenInternalID": {
"type": "string"
}
}
}
},
"messageTraits": {
"testContext": {
"headers": {
"type": "object",
"properties": {
"specversion": {
"description": "Description",
"type": "string",
"const": "1.0"
},
"type": {
"description": "Description",
"type": "string",
"minLength": 1
},
"source": {
"description": "Description",
"type": "string",
"format": "uri-reference"
},
"subject": {
"description": "Description",
"type": "string",
"minLength": 1
},
"id": {
"description": "Description",
"type": "string",
"minLength": 1,
"examples": [
"QgEK7wzuHtqdhJwqCS+VOA=="
]
},
"time": {
"description": "Description",
"type": "string",
"format": "date-time",
"examples": [
"2018-04-05T17:31:00Z"
]
},
"datacontenttype": {
"description": "Description",
"type": "string",
"const": "application/json"
}
},
"required": [
"id",
"specversion",
"source",
"type"
]
}
}
}
},
"externalDocs": {
"description": "Description",
"url": "https://help.sap.com/http.svc/ahp2/SAP_S4HANA_ON-PREMISE/2022.002/EN/30/96e09c79e24457b76ebdcaec944054/frameset.htm"
}
}

============

Below code we are using for AsyncAPI parser.

this is how we are using to parse the file.

final AMFBaseUnitClient asynchclient = AsyncAPIConfiguration.Async20().baseUnitClient();
final BaseUnit asynchUnresolvedModel =
asynchclient.parse("file://src/test/resources/testSchemas/reqRes/Test.json").get().baseUnit();
final BaseUnit asynchResolvedModel = asynchclient.transform(asynchUnresolvedModel).baseUnit();
final Document asynchDocument = (Document) asynchResolvedModel;
AsyncApi encodes = (AsyncApi) asynchDocument.encodes();
encodes.endPoints().forEach(endPoint -> {
endPoint.operations().forEach(operation -> {
System.out.println(operation.method().value());

	});
});
==================
And another one also we tried:

final AMFBaseUnitClient client = APIConfiguration.API().baseUnitClient();
final AMFParseResult parseResult = client.parseContent("src/test/resources/testSchemas/reqRes/OP_ALLERGENEVENTS.json").get();
final BaseUnit model = parseResult.baseUnit();
final DomainElement asyncApi = ((Document) model).encodes();

**Comment by tomsfernandez** [comment]
Hi @mkmishra89 I ran your example. We map AsyncApi channels to endpoints, subscriptions to operations and the "components" are in the "declares" of the BaseUnit. I'm closing this comment, thanks for asking.
