### ISSUE TITLE
Conversion of payload removes required array

### ISSUE THREAD

**Issue by golchha007** [aml-org/amf#1880]
Your issue may already be reported! Please search on Github issues before creating one.

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] question
  - [ ] other

* **What is the current behavior?**
While trying to get the payload for an endpoint, required array which is defined in Open API Specification is not returned by amf method.

* **If the current behavior is a bug, please provide the minimal steps to reproduce with AMF code. Please don't upload AMF code mixed with yours.**

The code to get the payload is : 

**String jsonSchema = JsonSchemaShapeRenderer.toJsonSchema((AnyShape) payload.schema(), OASConfiguration.OAS30());**

The value jsonSchema which we get from the amf method is a json string and is defined as : 

{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "$ref": "#/definitions/CommentCreationRequestModified",
    "definitions": {
        "CommentCreationRequestModified": {
            "allOf": [
                {
                    "$ref": "#/definitions/CommentPatchRequest"
                }
            ]
        },
        "CommentPatchRequest": {
            "additionalProperties": true,
            "type": "object",
            "properties": {
                "text": {
                    "description": "Comment content",
                    "type": "string",
                    "example": "Sample comment for demo."
                }
            }
        }
    }
}

The Open api specification has an end point whose request body and the respective references are defined as :

REQUEST BODY 
{
    "requestBody": {
        "content": {
            "application/json": {
                "schema": {
                    "$ref": "#/components/schemas/CommentCreationRequestModified"
                }
            }
        }
    }
}

REFERENCES 
{
    "components": {
        "schemas": {
            "CommentCreationRequestModified": {
                "allOf": [
                    {
                        "$ref": "#/components/schemas/CommentPatchRequest"
                    }
                ],
                "required": [
                    "text"
                ]
            },
            "CommentPatchRequest": {
                "type": "object",
                "properties": {
                    "text": {
                        "type": "string",
                        "description": "Comment content",
                        "example": "Sample comment for demo."
                    }
                }
            }
        }
    }
}

* **What is the expected behavior?**

The expected behavior is that the json string returned by amf method should have array named as "required" in object with key **CommentCreationRequestModified* as defined in the spec file.

* **What is the motivation/use case for changing the behavior? (for feature requests)**

* **Please tell us about your environment:**
  
  - AMF Version: 5.0.1
  - AMF Distribution: JVM
  - Operating System: Mac 13.5.2
  - Link to your project:

* **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, Gitter, etc)

**Comment by nschejtman** [comment]
Hi @golchha007 ,
try bumping to the latest AMF 5.4.3. We improved significantly our types resolution since AMF 5.3.0. If the issue still reproduces feel free to re-open this ticket.
