### ISSUE TITLE
Some exported top-level JS objects are not described in .d.ts

### ISSUE THREAD

**Issue by postatum** [aml-org/amf#354]
Some exported top-level JS objects are not described in `amf-client-js.d.ts`. In particular:
```
Aml10Parser
Aml10Renderer
ErrorHandler
ExecutionLog
JsServerFileResourceLoader
JsServerHttpResourceLoader
JsonPayloadRenderer
Oas30Resolver
SHACLValidator
YamlPayloadRenderer
```

**Comment by gutee** [comment]
We will not be updating the Typings for now, as we are currently developing a permanent and automated solution for this.
