### ISSUE TITLE
Validation has violation when defining named example in RAML overlay

### ISSUE THREAD

**Issue by wes566** [aml-org/amf#360]
1. use an overlay.raml to add a named example to a Type
2. use amf-client-js to validate with RAML validation profile

```js
const { results } = await amf.AMF.validate(
    model,
    amf.ProfileNames.RAML,
    amf.MessageStyles.RAML
);
```

Expected:
No violations (`results is empty`)

Actual:
`example-validation-error` violation is present (`results` has 1 violation present)

I have created a simple repro repo at https://github.com/wes566/amf-named-example-bug-repro

**Comment by tomsfernandez** [comment]
Hi @wes566. This issue was solved with https://github.com/aml-org/amf/pull/544. If you are using the JS distribution from NPM you will have to wait until AMF's next version that will be released on Wednesday 29th. Thanks for raising the issue.
