### ISSUE TITLE
Controling generated output with "SourceMap"

### ISSUE THREAD

**Issue by postatum** [aml-org/amf#363]
* **I'm submitting a ...**
  - [ ] question

Hi.

I was told that it's possible to use `SourceMap`s to somewhat resolve [this issue](https://github.com/aml-org/amf/issues/596). I was also told it's possible to provide a sourcemap to control the generated output.

Can you confirm this? If so, how do I properly use `SourceMap`s?

**Comment by nschejtman** [comment]
Hi @postatum, that link [https://github.com/aml-org/amf/issues/596](https://github.com/aml-org/amf/issues/596) seems to be pointing to our old repo. Could you help me identify the correct issue?

**Comment by postatum** [comment]
> Hi @postatum, that link https://github.com/aml-org/amf/issues/596 seems to be pointing to our old repo. Could you help me identify the correct issue?

Hi. Yes, it's the issue 596 in the old repo. It's been closed and not migrated to this repo.

**Comment by nschejtman** [comment]
Not sure if I understand what you mean by SourceMaps for this case. Maybe you mean render options?

**Comment by postatum** [comment]
Hi @nschejtman.

I mean [this thing](https://github.com/aml-org/amf/blob/develop/documentation/model.md#sourcemap). I don't know how and when to use them and whether they make sense in my situation. I'm trying to figure this out.

**Comment by nschejtman** [comment]
I don't see how you can use source maps to solve this issue. Nevertheless I think your best approach is what you mention in https://github.com/aml-org/amf/issues/364. Let's keep the discussion there. Closing this issue
