### ISSUE TITLE
Creating and using a custom Oas20Plugin

### ISSUE THREAD

**Issue by postatum** [aml-org/amf#364]
* **I'm submitting a ...**
  - [ ] question

Let's say I have a lib (written in Scala) which uses AMF and I want to create a custom `Oas20Plugin` to change the way OAS 2.0 emission works.

I imagine it as:
1. Copy and edit contents of `amf-webapi/shared/src/main/scala/amf/plugins/document/webapi/OasPlugin.scala`
2. Register new plugin with `amf.Core.loadPlugin()`.

My questions are:
I. Do the steps I described make sense?
II. If I follow these steps and use `Oas20Renderer` would my plugin take precedence over the default `Oas20Plugin`? Or should I also create a custom `Oas20Renderer`?

**Comment by postatum** [comment]
> Depends on what you want to achieve. What is your concrete use case?

I want to partially undo what was done by this commit  https://github.com/aml-org/amf/commit/f4a82948d76b7415e08130bd49f94612d6b39785. In particular, I want to create OAS 2-3 emitters/contexts/etc which would allow me to output OAS 2-3 the old way - without using "definitions" node.

**Comment by nschejtman** [comment]
Ok, is this blocking you to achieve what you need to achieve? Why do you need inlined definitions rather extracted definitions?

**Comment by postatum** [comment]
Hi @nschejtman. Thanks for answering this issue.

> Ok, is this blocking you to achieve what you need to achieve?

It does.

> Why do you need inlined definitions rather extracted definitions?

We have a lib [webapi-parser](https://github.com/raml-org/webapi-parser) which wraps AMF to provide users simplified interface. One of its features is the [resolution](https://raml-org.github.io/webapi-parser/resolving.html). In a nutshell it's a process of making specs super-flat - flattening types inheritance, moving types definitions to the places they are referenced from, etc.

With the addition of extracted definitions to OAS 2-3, "resolution" doesn't produce "flat" specs any more. I know it's a fault of emission logic and not resolution, but from users perspective it's the other way around.

You can find more details in the old AMF repo issue 596.

**Comment by nschejtman** [comment]
Great, I understand. Since you have already identified the commit I suggest that rather than extending the Oas20Plugin you parametrize this change in emission

**Comment by postatum** [comment]
Hi @nschejtman.

Thanks a lot for helping me with this!

Few questions:
1. What exactly should I parameterize? Should there be a switch to turn on/off this change in emission? Or a way to pass custom emitters/context/etc. through `Oas20Renderer -> Environment`? Any other way?
2. Should I make a PR to AMF with these changes or keep them in our lib?

**Comment by nschejtman** [comment]
1. Yes, a render option during emission would be the most correct choice
2. You can open us a PR with that improvement

**Comment by postatum** [comment]
>     1. Yes, a render option during emission would be the most correct choice
> 
>     2. You can open us a PR with that improvement

Understood. I'll work on this.
Thanks!

**Comment by postatum** [comment]
>     1. Yes, a render option during emission would be the most correct choice

One more question: should this option be just a boolean switch or a custom emitter class?

**Comment by nschejtman** [comment]
Boolean is OK. Closing this question, if you have any further questions feel free to reopen

**Comment by postatum** [comment]
Hi @nschejtman. I can't reopen this issue, but I got another quick question: How do I link local `amf-core` to local `amf`?

Considering I change something in `amf-core` locally, I want local `amf` to use the changed local `amf-core`.

**Comment by postatum** [comment]
@nschejtman please notice my previous comment :point_up:

**Comment by nschejtman** [comment]
@postatum Mi recommendation is to use source mode with the flag `-Dsbt.sourcemode=true`. 
Example for running a test suite `sbt -Dsbt.sourcemode=true "testOnly package.to.my.suite.MySuite"`

I suggest following the directory convention `~/mulesoft/amf` `~/mulesoft/amf-aml` `~/mulesoft/amf-core` so you don't have to configure paths manually

**Comment by postatum** [comment]
Hi again @nschejtman. I need more of your assistance :)

I tried running tests the way you suggested, but got an error:
```
$ sbt -Dsbt.sourcemode=true "test"
[info] Loading settings for project amf-build from plugins.sbt,assembly.sbt ...
[info] Loading project definition from /home/MYUSER/mulesoft/amf/project
[info] Loading settings for project amf from build.sbt ...
[info] Loading settings for project amf-aml-build from plugins.sbt ...
[info] Loading project definition from /home/MYUSER/mulesoft/amf-aml/project
[info] Loading settings for project amf-aml from build.sbt ...
[info] Loading settings for project amf-core-build from plugins.sbt ...
[info] Loading project definition from /home/MYUSER/mulesoft/amf-core/project
[info] Loading settings for project amf-core from build.sbt ...
[error] Invalid build URI (no handler available): file:///home/MYUSER/mulesoft/syaml/
[error] Use 'last' for the full log.
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? i
[warn] Ignoring load failure: no project loaded.
[error] Session not initialized.
[error] Use 'last' for the full log.
```

How do I handle this issue, considering I don't have access to `mulesoft/syaml` source code?

I also noticed `amf` can load dependencies from local ivy2. I tried releasing `amf-core` to local ivy2 with `sbt publishLocal`, but `amf` doesn't seem to pick up the `amf-core` released to local ivy2.

**Comment by postatum** [comment]
I've figured this out.
To make it work in the "source mode", I had to specify `syaml` as a regular dependency (`libraryDependencies`) instead of a source dependency (using `sbt-sriracha`'s `sourceDependency`). It was all done in `amf-core`.

**Comment by postatum** [comment]
@nschejtman hello again.

Does someone else work on this issue?
I've noticed that `compactEmission: Boolean` param has been added to `Oas3SpecEmitterContext` and `Oas2SpecEmitterContext` and is used in `OasCompactEmitterFactory`. It seems to do what we discussed here.
If so, is the work complete or is it in progress?
It the work is complete, how do I disable compacted emission now?

PS. The new param comes from this commit https://github.com/aml-org/amf/commit/4bcc683aca17693b70fcaaed7b39d996636f1f0f by @AgustinBettati

**Comment by AgustinBettati** [comment]
Hello @postatum! 
Your observation is correct, but this boolean has not been propagated to client interfaces as it is currently used internally.
You can add a boolean field in client RenderOptions and use that value within the specContext method in each OasPlugin when creating the appropriate context.

**Comment by postatum** [comment]
> Hello @postatum!
> Your observation is correct, but this boolean has not been propagated to client interfaces as it is currently used internally.

I see. Thanks for the answer!

> You can add a boolean field in client RenderOptions and use that value within the specContext method in each OasPlugin when creating the appropriate context.

Yep, that's what I was doing. There already seems to be a field in ShapeRenderOptions though - `ShapeRenderOptions.compactedEmission`.
