### ISSUE TITLE
core.Vendor constants are not exported to JS

### ISSUE THREAD

**Issue by postatum** [aml-org/amf#372]
* **I'm submitting a ...**
  - [ ] bug report

* **What is the current behavior?**
Constants on `core.Vendor` are not exported to JS. E.g. `RAML`, `RAML10`, `ASYNC20`, etc.

* **If the current behavior is a bug, please provide the minimal steps to reproduce with AMF code. Please don't upload AMF code mixed with yours.**

```node
> const amf = require('amf-client-js')
undefined
> amf.core.Vendor.RAML10
undefined
```

* **What is the expected behavior?**
`core.Vendor` constants should be exported similar to how constants are exported in `ProfileNames`, `MessageStyles`. I think it's a matter of adding `@JSExportAll` on top of the `Vendor` object.

* **Please tell us about your environment:**
  
  - AMF Version: 4.1.3
  - AMF Distribution: JS 
  - Operating System: Linux

---

I noticed this because I wanted to do a comparison like
```js
BaseUnit.sourceVendor === core.Vendor.RAML10
```
instead of doing
```js
BaseUnit.sourceVendor.toString() === 'RAML 1.0'
```

**Comment by nschejtman** [comment]
Hi @postatum I've created an internal Jira ticket for this case: [https://www.mulesoft.org/jira/browse/APIMF-2258](https://www.mulesoft.org/jira/browse/APIMF-2258)

**Comment by AgustinBettati** [comment]
Hello @postatum, the issue has been fixed and will be present in AMF's coming release scheduled for the 18th of November.
