### ISSUE TITLE
"Summary" / "Summaries" not supported in pluralize and singularize

### ISSUE THREAD

**Issue by Nathan-Smith** [aml-org/amf#404]
[InflectorBase](https://github.com/aml-org/amf/blob/master/amf-core/shared/src/main/scala/amf/core/utils/InflectorBase.scala) contains a number of plural, singular, irregular and uncountable rules. The word "Summary" should pluralize to "Summaries" and vice versa.

My suggestion is to update [InflectorBase](https://github.com/aml-org/amf/blob/master/amf-core/shared/src/main/scala/amf/core/utils/InflectorBase.scala) to include all the rules to the popular  [pluralize](https://www.npmjs.com/package/pluralize) library, the full list can be found [here](https://github.com/blakeembrey/pluralize/blob/master/pluralize.js#L266)

**Comment by gutee** [comment]
Jira issue to track progress: https://www.mulesoft.org/jira/browse/APIMF-1527

**Comment by gutee** [comment]
This is done and will be included in the next version of amf (3.2.2) due june 20th.
