### ISSUE TITLE
Validation of "protocols" is case-sensitive

### ISSUE THREAD

**Issue by postatum** [aml-org/amf#455]
`amf-client-js@3.1.8`

Consider this RAML
```raml
#%RAML 1.0
title: test
baseUri: api.example.com
protocols:
  - HTTP
  - hTTpS
```

When I parse and validate it, validation results say that:
```
Protocols must have a case insensitive value matching http or https`
```

Even though RAML 1.0 spec says `The protocols node MUST be a non-empty array of strings, of values HTTP and/or HTTPS, and is case-insensitive.`: https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#protocols

**Comment by BlockLucas** [comment]
https://www.mulesoft.org/jira/browse/APIMF-1509

**Comment by gutee** [comment]
Jira issue to track progress. @postatum Is this an issue coming from new raml tck?

**Comment by gutee** [comment]
Current amf version is 3.2.2. This is fixed for the next version.
