### ISSUE TITLE
Error "scala.MatchError: null" when trying to validate particular files

### ISSUE THREAD

**Issue by postatum** [aml-org/amf#456]
`amf-client-js@3.1.8`

When trying to validate these files after parsing I get an error saying `scala.MatchError: null`.

Files:
* [One](https://github.com/raml-org/raml-tck/blob/392211992e92c4d16dd2f117ecaafebb26b1f680/tests/raml-1.0/Annotations/root-09/valid-inheritance.raml)
* [Two](https://github.com/raml-org/raml-tck/blob/392211992e92c4d16dd2f117ecaafebb26b1f680/tests/raml-1.0/Annotations/other-01/valid-inherit-type.raml)
* [Three](https://github.com/raml-org/raml-tck/blob/392211992e92c4d16dd2f117ecaafebb26b1f680/tests/raml-1.0/Overlays/with-lib/aws-lib.raml)
* [Four](https://github.com/raml-org/raml-tck/blob/392211992e92c4d16dd2f117ecaafebb26b1f680/tests/raml-1.0/Overlays/with-lib/valid.raml)

JS code:
```js
const amf = require('amf-client-js')


async function main () {
  await amf.AMF.init()
  const model = await amf.AMF.raml10Parser().parseFileAsync(`file://./api.raml`)
  try {
    const report = await amf.AMF.validate(
      model, amf.ProfileNames.RAML10, amf.MessageStyles.RAML)
  } catch (e) {
    console.log(e.toString())
  }
  if (!report.conforms) {
    report.results.map(res => {
      console.log(`${res.level} - ${res.message}`)
    })
  }
}

main()
```

**Comment by BlockLucas** [comment]
https://www.mulesoft.org/jira/browse/APIMF-1510

**Comment by gutee** [comment]
Current amf version is 3.2.2. This is fixed for the next version.
