### ISSUE TITLE
Using type facets in union type

### ISSUE THREAD

**Issue by postatum** [aml-org/amf#460]
`amf-client-js@3.1.8`

When running following JS code to parse RAML below, I get a validation error saying:
`Properties maximum,minimum not supported in a RAML 1.0 unionShape node`

In RAML 1.0 spec I didn't find whether it's allowed or not to use properties like `maximum` in a declaration of type which is union of types that support that property. In this case both integer and number support `maximum`.

Does validation work correctly in this case? 

JS code:
```js
const amf = require('amf-client-js')

async function main () {
  await amf.AMF.init()
  const model = await amf.AMF.raml10Parser().parseFileAsync(`file://./api.raml`)
  try {
    const report = await amf.AMF.validate(
      model, amf.ProfileNames.RAML10, amf.MessageStyles.RAML)
  } catch (e) {
    console.log(e.toString())
  }
  if (!report.conforms) {
    report.results.map(res => {
      console.log(`${res.level} - ${res.message}`)
    })
  }
}

main()
```

RAML:
```raml
#%RAML 1.0
title: asd

types:
  Foo:
    type: integer|number
  Bar:
    type: Foo
    maximum: 2
    minimum: 1
```

**Comment by tomsfernandez** [comment]
Hi @postatum. The RAML spec states that:

> A union type is used to allow instances of data to be described by any of several types. A union type is declared via a type expression that combines 2 or more types delimited by pipe (|) symbols; these combined types are referred to as the union type's super types.

> An instance of a union type is valid if and only if it meets all restrictions associated with at least one of the super types. More generally, an instance of a type that has a union type in its type hierarchy is valid if and only if it is a valid instance of at least one of the super types obtained by expanding all unions in that type hierarchy.

This is why UnionShapes having properties doesn't make a lot of sense as they will never be taken into account in validation.

AMF throws violation when declaring facets for UnionTypes

**Comment by tomsfernandez** [comment]
I'm closing this issue
