### ISSUE TITLE
Swagger $ref not properly resolved

### ISSUE THREAD

**Issue by deepaksuseelan** [aml-org/amf#462]
Using AMF client 2.12 version 3.1.8 the below swagger definition

definitions:
  subhousehold:
    type: object
      properties:
       profile:
         $ref: '#/definitions/Profile'

produces in RAML 1.0 as

subhousehold:
  type: object
  properties:
    profile: "#/definitions/Profile"

The part #/definitions/Profile isnt resolved correctly.

**Comment by gutee** [comment]
@deepaksuseelan The API does not work as '#/definitions/Profile' is not defined in the scope of the definitions. Besides the validation error, we can only ignore the ref and take the string into the model.
