### ISSUE TITLE
CLI Usage Documentation Improvement Request

### ISSUE THREAD

**Issue by deduper** [aml-org/amf#463]
I'd never heard of this project until a couple days ago. The AMF parser sounds like a super improvement over other existing API parsers out there.

After skimming [_the documentation_](https://a.ml/) and spending a little time in [_the playground_](https://a.ml/amf-playground/vocabularies.html), I eventually landed here in the repo.

The [_installation and usage section_](https://github.com/aml-org/amf#command-line-usage) of the README is helpful. But it would be even better, in my opinion, if the `java -jar` CLI examples added two or three words about what the `parse <input_file> -in FORMAT` command will output.

TIA :)

**Comment by tomsfernandez** [comment]
Hi @deduper. It would be great if you could submit a PR improving the docs! If you do please link this issue and we will continue discussing it in the PR.

**Comment by tomsfernandez** [comment]
I'm closing this issue. Please create a PR if you want to collaborate to the project's documentation.
