### ISSUE TITLE
Ignored RAML issue: Empty protocols array or a single string

### ISSUE THREAD

**Issue by postatum** [aml-org/amf#464]
### Issue
Running code below should fail or report validation error because according to RAML 1.0 spec it parses and validates an invalid RAML string.

The spec says:
> The protocols node MUST be a non-empty array of strings, of values HTTP and/or HTTPS, and is case-insensitive.

Spec link: https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#protocols

### amf-client-js version
3.1.9

### javascript code

Node: This is also true for protocols value of: `protocols: HTTP`.

```js
const amf = require('amf-client-js')

const ramlStr = `
#%RAML 1.0
title: test
baseUri: api.example.com
protocols: [ ]
`

async function main () {
  await amf.AMF.init()
  const model = await amf.AMF.raml10Parser().parseStringAsync(ramlStr)
  let report
  try {
    report = await amf.AMF.validate(
      model, amf.ProfileNames.RAML10, amf.MessageStyles.RAML)
  } catch (e) {
    console.log(e.toString())
  }
  if (!report.conforms) {
    report.results.map(res => {
      console.log(`${res.level} - ${res.message}`)
    })
  }
}

main()
```

**Comment by BlockLucas** [comment]
https://www.mulesoft.org/jira/browse/APIMF-1512

**Comment by gutee** [comment]
Current amf version is 3.2.2. This is fixed for the next version. The part where a string is also valid will not be fixed because of backwards compatibility.
