### ISSUE TITLE
Ignored RAML issue: Invalid mediaType values

### ISSUE THREAD

**Issue by postatum** [aml-org/amf#465]
### Issue
Running code below should fail or report validation error because according to RAML 1.0 spec it parses and validates an invalid RAML string.

The spec says:
> Each [mediaType] value needs to conform to the media type specification in RFC6838.

Spec link:
https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#default-media-types

### amf-client-js version
3.1.9

### javascript code

Same issue is true for a different array format: `mediaType: [ sdfsdf/json , application/xml ]`.

```js
const amf = require('amf-client-js')

const ramlStr = `
#%RAML 1.0
title: Test Api
mediaType:
  - fwfefwf/xml
  - application/json
`

async function main () {
  await amf.AMF.init()
  const model = await amf.AMF.raml10Parser().parseStringAsync(ramlStr)
  let report
  try {
    report = await amf.AMF.validate(
      model, amf.ProfileNames.RAML10, amf.MessageStyles.RAML)
  } catch (e) {
    console.log(e.toString())
  }
  if (!report.conforms) {
    report.results.map(res => {
      console.log(`${res.level} - ${res.message}`)
    })
  }
}

main()
```

**Comment by gutee** [comment]
@postatum 'fwfefwf/xml' conforms with RFC6838 because it has the structure of a valid media type, the only thing is that it is not registered as one of the standards, but it is valid.
