### ISSUE TITLE
Ignored RAML issue: Invalid number format value

### ISSUE THREAD

**Issue by postatum** [aml-org/amf#468]
### Issue
Running code below with each of the RAML inputs provided should fail or report validation error because according to RAML 1.0 spec provided RAML inputs are invalid.

The spec says:
> The format of the value. The value MUST be one of the following: int32, int64, int, long, float, double, int16, int8

Spec link:
https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#number

### amf-client-js version
3.1.9

### RAML Inputs
```raml
#%RAML 1.0
title: Some API

types:
    SomeType:
        type: number
        format: asdasdasd
        multipleOf: 1
        minimum: 1
        maximum: 10
```

### JavaScript Code
```js
const amf = require('amf-client-js')

const ramlStr = ''  // Pick one of the above RAML inputs

async function main () {
  await amf.AMF.init()
  const model = await amf.AMF.raml10Parser().parseStringAsync(ramlStr)
  let report
  try {
    report = await amf.AMF.validate(
      model, amf.ProfileNames.RAML10, amf.MessageStyles.RAML)
  } catch (e) {
    console.log(e.toString())
  }
  if (!report.conforms) {
    report.results.map(res => {
      console.log(`${res.level} - ${res.message}`)
    })
  }
}

main()
```

**Comment by gutee** [comment]
This has already been discussed, a warning has been added and the invalid format is ignored (https://www.mulesoft.org/jira/browse/APIMF-1059).
