### ISSUE TITLE
Ignored RAML issue: Invalid file.max(min)Length value

### ISSUE THREAD

**Issue by postatum** [aml-org/amf#469]
### Issue
Running code below with each of the RAML inputs provided should fail or report validation error because according to RAML 1.0 spec provided RAML inputs are invalid.

The spec says:
> Specifies the maximum number of bytes for a parameter value. The value MUST be equal to or greater than 0.

Spec link:
https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#file

### amf-client-js version
3.1.9

### RAML Inputs
```raml
#%RAML 1.0
title: Some API

types:
  userPicture:
    type: file
    fileTypes: ['image/jpeg', 'image/png']
    maxLength: -1
  customFile:
    type: file
    fileTypes: ['*/*']
    maxLength: -2
```

### JavaScript Code
```js
const amf = require('amf-client-js')

const ramlStr = ''  // Pick one of the above RAML inputs

async function main () {
  await amf.AMF.init()
  const model = await amf.AMF.raml10Parser().parseStringAsync(ramlStr)
  let report
  try {
    report = await amf.AMF.validate(
      model, amf.ProfileNames.RAML10, amf.MessageStyles.RAML)
  } catch (e) {
    console.log(e.toString())
  }
  if (!report.conforms) {
    report.results.map(res => {
      console.log(`${res.level} - ${res.message}`)
    })
  }
}

main()
```

**Comment by BlockLucas** [comment]
https://www.mulesoft.org/jira/browse/APIMF-1517

**Comment by gutee** [comment]
This is fixed and will be available in the next version of amf.
