### ISSUE TITLE
Ignored RAML issue: Making subtype property optional

### ISSUE THREAD

**Issue by postatum** [aml-org/amf#471]
### Issue
Running code below with each of the RAML inputs provided should fail or report validation error because according to RAML 1.0 spec provided RAML inputs are invalid.

The spec says:
> A sub-type can override properties of its parent type with the following restrictions: 1) a required property in the parent type cannot be changed to optional in the sub-type, and ...

Spec link:
https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#object-type-specialization

### amf-client-js version
3.1.9

### RAML Inputs
```raml
#%RAML 1.0
title: Test API
types:
  MyType1:
    properties:
      name: string
  MyType2:
    type: MyType1
    properties:
      name?: string
```

### JavaScript Code
```js
const amf = require('amf-client-js')

const ramlStr = ''  // Pick one of the above RAML inputs

async function main () {
  await amf.AMF.init()
  const model = await amf.AMF.raml10Parser().parseStringAsync(ramlStr)
  let report
  try {
    report = await amf.AMF.validate(
      model, amf.ProfileNames.RAML10, amf.MessageStyles.RAML)
  } catch (e) {
    console.log(e.toString())
  }
  if (!report.conforms) {
    report.results.map(res => {
      console.log(`${res.level} - ${res.message}`)
    })
  }
}

main()
```

**Comment by gutee** [comment]
@postatum A warning is being placed in the property when it is optional.

**Comment by tomsfernandez** [comment]
Hi @postatum. I'm closing this issue as it is a "violation" level validation since at least AMF version 4.0.0 (as you stated in issue aml-org/amf#423 ).
I tested it in amf version 4.1.2 just in case and it is working as expected.

P.D: I couldn't replicate it in 3.1.9 JS.
