### ISSUE TITLE
Ignored RAML issue: Using descriminator inline

### ISSUE THREAD

**Issue by postatum** [aml-org/amf#475]
### Issue
Running code below should fail or report validation error because according to RAML 1.0 spec provided RAML input is invalid.

The spec says:
> Neither discriminator nor discriminatorValue can be defined for any inline type declarations or union types.

Spec link:
https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md/#using-discriminator

### AMF Version
4.0.0-SNAPSHOT

### Code
```sh
$ java -jar amf-4.0.0-SNAPSHOT.jar validate -in "RAML 1.0" -mime-in "application/yaml" -p "RAML" file://api.raml
{
  "@type": "http://www.w3.org/ns/shacl#ValidationReport",
  "http://www.w3.org/ns/shacl#conforms": true
}
```

### api.raml
```raml
#%RAML 1.0
title: API

baseUri: /some/base/uri

/someUri:
  get:
    responses:
      200:
        body:
          application/json:
             discriminator: kind
             properties:
               kind: string
```

**Comment by tomsfernandez** [comment]
Hi @postatum . I have replicated the issue in amf version 4.1.2 JS distribution. I have created an internal ticket to track this. We will provide further updates in this Github issue thread.

The internal ticket is: https://www.mulesoft.org/jira/browse/APIMF-2176

**Comment by tomsfernandez** [comment]
Hi @postatum. After speaking with the rest of the AMF team we have decided this is part of the current AMF behaviour. We have no short term plans to change it. I'm closing this issue and the closing the related internal ticket too.
