### ISSUE TITLE
Facet name begins with open parenthesis

### ISSUE THREAD

**Issue by postatum** [aml-org/amf#481]
### Issue
Running code below should fail or report validation error because according to RAML 1.0 spec provided RAML input is invalid.

The spec says:
> Facet names MUST NOT begin with open parenthesis, to disambiguate the names from annotations.

Spec link:
https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md/#user-defined-facets

### AMF Version
4.0.0-SNAPSHOT

### Code
```sh
$ java -jar amf-4.0.0-SNAPSHOT.jar validate -in "RAML 1.0" -mime-in "application/yaml" -p "RAML" file://api.raml
{
  "@type": "http://www.w3.org/ns/shacl#ValidationReport",
  "http://www.w3.org/ns/shacl#conforms": true
}
```

### api.raml
```raml
#%RAML 1.0
title: A

types:
  CustomDate:
    type: string
    facets:
      (format: string
  Year:
    type: CustomDate
    (format: YYYY

/search:
  get:
    queryParameters:
      y: Year
```

**Comment by gutee** [comment]
This is fixed and stated for 4.0.0 release
