### ISSUE TITLE
Using invalid method-level protocols

### ISSUE THREAD

**Issue by postatum** [aml-org/amf#486]
### Issue
Running code below should fail or report validation error because according to RAML 1.0 spec provided RAML input is invalid.

The spec says:
> Explicitly specify the protocol(s) used to invoke a method, thereby overriding the protocols set elsewhere, for example in the baseUri or the root-level protocols node.
> ...
> The protocols node MUST be a non-empty array of strings, of values HTTP and/or HTTPS, and is case-insensitive.

Spec link:
https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md/#methods

### AMF Version
4.0.0-SNAPSHOT

### Code
```sh
$ java -jar amf-4.0.0-SNAPSHOT.jar validate -in "RAML 1.0" -mime-in "application/yaml" -p "RAML" file://api.raml
{
  "@type": "http://www.w3.org/ns/shacl#ValidationReport",
  "http://www.w3.org/ns/shacl#conforms": true
}
```

### api.raml
```raml
#%RAML 1.0
title: test
/test:
  post:
    protocols: ASDASDASD
    body:
      application/json:
    responses:
      201:
```

```raml
#%RAML 1.0
title: test
/test:
  post:
    protocols: [HTTP, FTP, SMTP]
    body:
      application/json:
    responses:
      201:
```

**Comment by BlockLucas** [comment]
https://www.mulesoft.org/jira/browse/APIMF-1521

**Comment by gutee** [comment]
Current amf version is 3.2.2. This is fixed for the next version.
