### ISSUE TITLE
Using invalid media type in method body

### ISSUE THREAD

**Issue by postatum** [aml-org/amf#487]
### Issue
Running code below should fail or report validation error because according to RAML 1.0 spec provided RAML input is invalid.

The spec says:
> Generally, the body declaration is a map whose key names are the valid media types of the request body. Each key name MUST be a media type string conforming to the media type specification in RFC6838

Spec link:
https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md/#bodies

### AMF Version
4.0.0-SNAPSHOT

### Code
```sh
$ java -jar amf-4.0.0-SNAPSHOT.jar validate -in "RAML 1.0" -mime-in "application/yaml" -p "RAML" file://api.raml
{
  "@type": "http://www.w3.org/ns/shacl#ValidationReport",
  "http://www.w3.org/ns/shacl#conforms": true
}
```

### api.raml
```raml
#%RAML 1.0
title: test
/test:
  post:
    body:
      hi/json:
```

Same is true for response bodies

```raml
#%RAML 1.0
title: test
/test:
  post:
    responses:
      200:
        body:
          bananas/json:
```

**Comment by gutee** [comment]
Duplicated from #465
