### ISSUE TITLE
Applying transformation functions without a pipe (|)

### ISSUE THREAD

**Issue by postatum** [aml-org/amf#489]
### Issue
Running code below should fail or report validation error because according to RAML 1.0 spec provided RAML input is invalid.

The spec says:
> Append these functions to the parameter name within the double angle brackets, separated by a pipe (|) character and optional whitespace padding.

Spec link:
https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md/#resource-type-and-trait-parameters

### AMF Version
4.0.0-SNAPSHOT

### Code
```sh
$ java -jar amf-4.0.0-SNAPSHOT.jar validate -in "RAML 1.0" -mime-in "application/yaml" -p "RAML" file://api.raml
{
  "@type": "http://www.w3.org/ns/shacl#ValidationReport",
  "http://www.w3.org/ns/shacl#conforms": true
}
```

### api.raml
```raml
#%RAML 1.0
title: Test
version: 1
baseUri: /api/{version}
traits:
  notAlwaysPresent:
    responses:
      401:
        description:  <<param !upperunderscorecase>> cannot be found
/users:
  get:
    is: [ { notAlwaysPresent : {param : user } }]
```

**Comment by gutee** [comment]
@postatum what if I want to name my parameter 'param !upperunderscorecase'? What is the naming restriction. If it has no pipe, it means no transformation has been used
