### ISSUE TITLE
Using value of incorrect type in annotation

### ISSUE THREAD

**Issue by postatum** [aml-org/amf#493]
### Issue
Running code below should fail or report validation error because according to RAML 1.0 spec provided RAML input is invalid.

The spec says:
> The annotation value MUST be valid according to the corresponding annotation type.

Spec link:
https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md/#applying-annotations

### AMF Version
4.0.0-SNAPSHOT

### Code
```sh
$ java -jar amf-4.0.0-SNAPSHOT.jar validate -in "RAML 1.0" -mime-in "application/yaml" -p "RAML" file://api.raml
{
  "@type": "http://www.w3.org/ns/shacl#ValidationReport",
  "http://www.w3.org/ns/shacl#conforms": true
}
```

### api.raml
```raml
#%RAML 1.0
title: API
annotationTypes:
  a1: number
  a2: boolean

/resource:
  description:
    value: descriptionValue
    (a1): 5

  displayName:
    value: myResource
    (a2): value1
```

**Comment by BlockLucas** [comment]
https://www.mulesoft.org/jira/browse/APIMF-1524

**Comment by gutee** [comment]
This is fixed and will be available in the next amf version.
