### ISSUE TITLE
Annotation value minimum/maximum constraint is not validated

### ISSUE THREAD

**Issue by postatum** [aml-org/amf#494]
### Issue
Running code below should fail or report validation error because according to RAML 1.0 spec provided RAML input is invalid.

The spec says:
> An annotation type declaration constrains the value of an annotation of that type just as a data type declaration constrains the value of a URI parameter, query parameter, header, or body of that type.

Spec link:
https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md/#declaring-annotation-types

### AMF Version
4.0.0-SNAPSHOT

### Code
```sh
$ java -jar amf-4.0.0-SNAPSHOT.jar validate -in "RAML 1.0" -mime-in "application/yaml" -p "RAML" file://api.raml
{
  "@type": "http://www.w3.org/ns/shacl#ValidationReport",
  "http://www.w3.org/ns/shacl#conforms": true
}
```

### api.raml
maximum
```raml
#%RAML 1.0
annotationTypes:
  z:
    type: number
    maximum: 10
title:
  value: Hello
  (z): 11
```

minimum
```raml
#%RAML 1.0
annotationTypes:
  z:
    type: number
    minimum: 2
title:
  value: Hello
  (z): 1
```

**Comment by gutee** [comment]
Duplicated from #493
