### ISSUE TITLE
Annotation value properties arent validated against its definition

### ISSUE THREAD

**Issue by postatum** [aml-org/amf#495]
### Issue
Running code below should fail or report validation error because according to RAML 1.0 spec provided RAML input is invalid.

The spec says:
> The annotation value MUST be valid according to the corresponding annotation type.

Spec link:
https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md/#applying-annotations

### AMF Version
4.0.0-SNAPSHOT

### Code
```sh
$ java -jar amf-4.0.0-SNAPSHOT.jar validate -in "RAML 1.0" -mime-in "application/yaml" -p "RAML" file://api.raml
{
  "@type": "http://www.w3.org/ns/shacl#ValidationReport",
  "http://www.w3.org/ns/shacl#conforms": true
}
```

### api.raml
```raml
#%RAML 1.0
title: Test API

annotationTypes:
  bindingDefinition:
    displayName: BindingDefinition
    type: array
    items:
      properties:
        method: string

types:
  Cards:
    type: array
    items:
      properties:
        cardId:
          (bindingDefinition):
            - method: "GET"
              iDontExist: 1
          type: string
```

**Comment by gutee** [comment]
The annotation value is valid against the annotation type, as the type has additionalProperties in true by default, so iDontExist is valid that type's properties
