### ISSUE TITLE
Defining nested resource in resourceType

### ISSUE THREAD

**Issue by postatum** [aml-org/amf#499]
### Issue
Running code below should fail or report validation error because according to RAML 1.0 spec provided RAML input is invalid.

The spec says:
> A resource type, like a resource, can specify security schemes, methods, and other nodes. ... A resource type definition cannot be used to generate nested resources when the definition is applied to a resource.

Spec link:
https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md/#resource-types-and-traits

### AMF Version
4.0.0-SNAPSHOT

### Code
```sh
$ java -jar amf-4.0.0-SNAPSHOT.jar validate -in "RAML 1.0" -mime-in "application/yaml" -p "RAML" file://api.raml
{
  "@type": "http://www.w3.org/ns/shacl#ValidationReport",
  "http://www.w3.org/ns/shacl#conforms": true
}
```

### api.raml
```raml
#%RAML 1.0
title: Invalid sub resource usage

resourceTypes:
  hasGroups:
    get:
    patch:
    delete:
    /groups:
```

**Comment by gutee** [comment]
Duplicated from #497
