### ISSUE TITLE
Included JSON schema is not validated

### ISSUE THREAD

**Issue by postatum** [aml-org/amf#502]
### Issue
Running code below should fail or report validation error because according to RAML 1.0 spec provided RAML input is invalid.

**In particular the issue is that included JSON schema is not validated. In this example JSON Schema definitions reference non-existing definitions.**

The spec says:
> A RAML processor MUST be able to interpret and apply JSON Schema and XML Schema.

Spec link:
https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md/#using-xml-and-json-schema

### AMF Version
4.0.0-SNAPSHOT

### Code
```sh
$ java -jar amf-4.0.0-SNAPSHOT.jar validate -in "RAML 1.0" -mime-in "application/yaml" -p "RAML" file://api.raml
{
  "@type": "http://www.w3.org/ns/shacl#ValidationReport",
  "http://www.w3.org/ns/shacl#conforms": true
}
```

### api.raml
```raml
#%RAML 1.0
title: testing json schemas validation

resourceTypes:
  test:
    get:
      responses:
        201:
          body:
            application/json:
              type: !include invalid-list.json
```
invalid-list.json
```json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "list.json",
  "type": "object",
  "allOf": [
    {
      "$ref": "#/definitions/a"
    }
  ]  ,
  "definitions": {
  	"a":{
  	  "id": "#a",
  	  "type": "object",
  	  "allOf": [
  	    {
  	      "$ref": "#/definitions/BusinessModelObject"
  	    }
  	  ],
  	  "properties": {
  	  	  "a": {
  	      "$ref": "#/definitions/b"
  	    }
  	  },
  	  "required": ["a"]
  	}
  }
}
```

**Comment by gutee** [comment]
Duplicated by #497
