### ISSUE TITLE
Overriding built-in facets is allowed

### ISSUE THREAD

**Issue by postatum** [aml-org/amf#503]
### Issue
Running code below should fail or report validation error because according to RAML 1.0 spec provided RAML input is invalid.

The spec says:
> User-defined facet names on a type MUST NOT match built-in facets on that type, nor facet names of any ancestor type in the inheritance chain of the type.

Spec link:
https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md/#user-defined-facets

### AMF Version
4.0.0-SNAPSHOT

### Code
```sh
$ java -jar amf-4.0.0-SNAPSHOT.jar validate -in "RAML 1.0" -mime-in "application/yaml" -p "RAML" file://api.raml
{
  "@type": "http://www.w3.org/ns/shacl#ValidationReport",
  "http://www.w3.org/ns/shacl#conforms": true
}
```

### api.raml
```raml
#%RAML 1.0
title: type example
version: 1

types:
  ResourceLink:
    description: a description
    facets:
      a: string
      b: number
      properties: integer
      description: string
    properties:
      href: string
      rel:
        enum: [self, next, prev]
      method:
        default: get
        required: false
```

**Comment by gutee** [comment]
Duplicated by #479
