### ISSUE TITLE
Descriminator kind value is not validated

### ISSUE THREAD

**Issue by postatum** [aml-org/amf#506]
### Issue
Running code below should fail or report validation error because according to RAML 1.0 spec provided RAML input is invalid.

**Spec says nothing about validating discriminator property values so I'm not certain whether it's a bug or not.**

### AMF Version
4.0.0-SNAPSHOT

### Code
```sh
$ java -jar amf-4.0.0-SNAPSHOT.jar validate -in "RAML 1.0" -mime-in "application/yaml" -p "RAML" file://api.raml
{
  "@type": "http://www.w3.org/ns/shacl#ValidationReport",
  "http://www.w3.org/ns/shacl#conforms": true
}
```

### api.raml
```raml
#%RAML 1.0
title: Discriminator
mediaType: application/json
uses:
  model: example-library.raml

/persons{id}:
    get:
     responses:
      200:
        body:
          type: model.Person[]
          example:
            strict: false
            value:
              - name: A User
                userId: "111"
                kind: user
              - name: An Employee
                employeeId: "222"
                kind: administrator
```
### example-library.raml
```raml
#%RAML 1.0 Library
types:
  Person:
    type: object
    discriminator: kind
    properties:
      name: string
      kind: string
  User:
    type: Person
    discriminatorValue: user
    properties:
      userId: string
```

**Comment by nschejtman** [comment]
This is not a bug. 

We will NOT validate the value of discriminator properties further than the validations imposed on the property itself (in the example above, that it is a string). If the value of the discriminator property does not match any type we will not show any validations.

Examples will ALWAYS be validated against the type for which that example has been defined. In the above example, against an array of Person. Recall that by default _additionalProperties_ is true for all type and therefore _userId_ and _employeeId_ are both valid properties for the Person type.

**Comment by jstoiko** [comment]
I confirm this is not a bug as far as RAML is concerned. The RAML 1.0 spec does not constrain or impose any sort of validation on  the value of an object property referred by the ‘discriminator’ facet.
