### ISSUE TITLE
Defining discriminator inline

### ISSUE THREAD

**Issue by postatum** [aml-org/amf#508]
### Issue
Running code below should fail or report validation error because according to RAML 1.0 spec provided RAML input is invalid.

The spec says:
> Neither discriminator nor discriminatorValue can be defined for any inline type declarations or union types.

Spec link:
https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md/#using-discriminator

### AMF Version
4.0.0-SNAPSHOT

### Code
```sh
$ java -jar amf-4.0.0-SNAPSHOT.jar validate -in "RAML 1.0" -mime-in "application/yaml" -p "RAML" file://api.raml
{
  "@type": "http://www.w3.org/ns/shacl#ValidationReport",
  "http://www.w3.org/ns/shacl#conforms": true
}
```

### api.raml
```raml
#%RAML 1.0

title: Discriminator

/person:
  get:
    responses:
      200:
        body:
          application/json:
            discriminator: lala
            properties:
              lala: string
```

**Comment by gutee** [comment]
Duplicated from #475
