### ISSUE TITLE
Extending type creates cyclic dependency

### ISSUE THREAD

**Issue by postatum** [aml-org/amf#510]
### Issue
Running code below should fail or report validation error because according to RAML 1.0 spec provided RAML input is invalid.

The spec says:
> Extending types MUST NOT create any cyclic dependencies.

Spec link:
https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md/#introduction-1

**Not sure if this is considered "extending" though.**

### AMF Version
4.0.0-SNAPSHOT

### Code
```sh
$ java -jar amf-4.0.0-SNAPSHOT.jar validate -in "RAML 1.0" -mime-in "application/yaml" -p "RAML" file://api.raml
{
  "@type": "http://www.w3.org/ns/shacl#ValidationReport",
  "http://www.w3.org/ns/shacl#conforms": true
}
```

### api.raml
```raml
#%RAML 1.0
title: API

types:
  SomeType:
    type: SomeType[]
```
and
```raml
#%RAML 1.0
title: API

types:
  SomeType:
    type: object | SomeUnion

  SomeUnion:
    type: AnotherType[] | OneMoreType[]

  AnotherType:
    type: SomeType

  OneMoreType:
    type: AnotherType
```

**Comment by gutee** [comment]
This is not cyclic, as the type can be constructed (reaching a simple object type at the end in 'SomeType')
