### ISSUE TITLE
Overlay adds trait nodes

### ISSUE THREAD

**Issue by postatum** [aml-org/amf#513]
### Issue
Running code below should fail or report validation error because according to RAML 1.0 spec provided RAML input is invalid.

The spec says:
> Any differences in the documents MUST be only in the nodes listed in the following table.

Spec link:
https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md/#overlays

### AMF Version
4.0.0-SNAPSHOT

### Code
```sh
$ java -jar amf-4.0.0-SNAPSHOT.jar validate -in "RAML 1.0" -mime-in "application/yaml" -p "RAML" file://api.raml
{
  "@type": "http://www.w3.org/ns/shacl#ValidationReport",
  "http://www.w3.org/ns/shacl#conforms": true
}
```

### api.raml
```raml
#%RAML 1.0 Overlay
title: Overlay 1
extends: base.raml
traits:
  env-org-pair:
    headers:
        Hi: string
```

### base.raml
```raml
#%RAML 1.0
title: hybrid-rest-services
version: 0.4
mediaType: application/json
securedBy: x-ttt
protocols: HTTP
baseUri: https://anypoint.mulesoft.com/hybrid/api/v1
traits:
   env-org-pair:
      displayName: masterDisplayName
```

**Comment by gutee** [comment]
Duplicated by #498
