### ISSUE TITLE
Referencing library name inside a library is required to correctly process API

### ISSUE THREAD

**Issue by jarrodek** [aml-org/amf#522]
The issue is originally reported in API Console project: https://github.com/mulesoft/api-console/issues/611

Consider the following example: 

api.raml: 

```yaml
#%RAML 1.0
title: Example
version: 1.0

uses:
  lib: lib.raml

/foo:
  type: lib.fooendpoint
```

lib.raml

```yaml
#%RAML 1.0 Library

traits:
  ServerError:
    responses:
      500:
        description: This is 500 error.
        body:
          application/json:
            type: ErrorHolder

types:
  ErrorHolder:
    type: object
    properties:
      errors:
        type: object[]

resourceTypes:
  fooendpoint:
    get:
      is:
        - ServerError
```

In this example the `errors` property is not rendered by the console. But when `fooendpoint` resource type use is changed to `lib.ServerError` then it works.

The problem is at this point when you are building library, probably with intention to share across a team, you cannot assume the name that will be used for the library. Also it's just doesn't make any sense to do so. Initially I've talked to @antoniogarrote about this issue and apparently there are two ways of parsing libraries and we have chosen to use the one that causes this problem. I hope we can revisit this decision to fix the issue.

**Comment by nschejtman** [comment]
Jira issue: https://www.mulesoft.org/jira/browse/APIMF-1534

**Comment by AgustinBettati** [comment]
The console is rendering the errors property as expected, it is likely that there has been a fix related to references within libraries.
