### ISSUE TITLE
Array type determined

### ISSUE THREAD

**Issue by postatum** [aml-org/amf#524]
### Issue
Running code below should fail or report validation error because there are no rules in RAML 1.0 to determine array type.

Spec link:
https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md/#determine-default-types

### amf-client-js version
3.2.0

### javascript code

Same code as here https://github.com/aml-org/amf/issues/469

### RAML
Note how this RAML spec is missing `type: array`.

```raml
#%RAML 1.0
title: Albums API
version: v1

/released-albums:
  get:
    responses:
      200:
        body:
          application/json:
            items:
              type: object
              additionalProperties: true
              properties:
                title:
                  type: string
                  required: true
                songs:
                  items:
                    additionalProperties: true
                    properties:
                      title:
                        type: string
                        required: true
                  required: true
```

**Comment by gutee** [comment]
We make an inference of type when unique facets of each type is used, that is why it's not asked

**Comment by gutee** [comment]
This will be fixed in the spec with this: https://github.com/raml-org/raml-spec/issues/710
