### ISSUE TITLE
With AMF 4.1.3, the generated amf graph has inconsistent reference node ids though the content is same

### ISSUE THREAD

**Issue by unandyala** [aml-org/amf#528]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] question
  - [ ] other

* **What is the current behavior?**
I have two ramls with same content except that one raml is missing an endpoint
![image (2)](https://user-images.githubusercontent.com/59447810/87441767-7f1a2000-c5c1-11ea-96cc-90882deab5d3.png)

With AMF 4.1.3, reference node IDs between the ramls are different though the content is same
![image (3)](https://user-images.githubusercontent.com/59447810/87441806-8a6d4b80-c5c1-11ea-9048-1ca3766e0ff5.png)

**Note:** With AMF 4..1.2, node Ids were consistent
![image (4)](https://user-images.githubusercontent.com/59447810/87441927-ac66ce00-c5c1-11ea-9541-313d18d80b13.png)

* **What is the expected behavior?**
Node Ids needs to be consistent when the content is same

* **What is the motivation/use case for changing the behavior? (for feature requests)**
We are developing a differencing tool to compare two RAML specs using AMF graphs

* **Please tell us about your environment:**
  
  - AMF Version: 4.1.3
  - AMF Distribution:  JS 
  - Operating System: macOS

**Comment by nschejtman** [comment]
APIMF-2263 has been created to track internally this issue in our Jira.

**Comment by nschejtman** [comment]
This issue has been fixed and will be available in our next release (July 29th 2020)
