### ISSUE TITLE
Incorrect fixpoint property name on Recursive Shape

### ISSUE THREAD

**Issue by pmdartus** [aml-org/amf#533]
In the generated `amf-client-js.d.ts` type definition the `model.domain.RecursiveShape` references `fixPoint` while it should reference `fixpoint`.

https://github.com/aml-org/amf/blob/e24fa66e09386a4c046cc617a5cf538f04a810b5/amf-client/js/typings/amf-client-js.d.ts#L940

Also, I am not able to find the Scala class definition for `RecursiveShape` in this repository. Where is this class defined?

**Comment by gutee** [comment]
This will be fixed in the next amf js release (current version is 3.2.2)
