### ISSUE TITLE
Incorrect json schema produced from RAML "type: file"

### ISSUE THREAD

**Issue by postatum** [aml-org/amf#539]
With amf-client-js@3.2.2

Running code [1] produces output [2].
Note that it converts RAML `type: file` to JSON Schema ` "type": "file"` even though [there's no type `file`](https://json-schema.org/latest/json-schema-validation.html#rfc.section.6.1.1) in JSON Schema draft 04. Thus it produces not valid draft4 schema.

Files should be represented using `type:string` and [contentEncoding](https://json-schema.org/latest/json-schema-validation.html#rfc.section.8.3).

Maybe it's caused by the fact that OAS 2.0 has a type `file`? See [this](https://swagger.io/docs/specification/data-models/data-types/#file).

[1]
```js
const amf = require('amf-client-js')

const ramlStr = `
#%RAML 1.0 Library
types:
  Banana:
    properties:
      photo:
        type: file
        fileTypes: ['image/jpeg', 'image/png']
        minLength: 1
        maxLength: 307200
`

async function main () {
  await amf.AMF.init()
  const model = await amf.AMF.raml10Parser().parseStringAsync(ramlStr)
  const banana = model.findById('http://a.ml/amf/default_document#/declarations/types/Banana')
  console.log(banana.toJsonSchema)
}

main()
```

[2]
```json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "$ref": "#/definitions/Banana",
  "definitions": {
    "Banana": {
      "required": [
        "photo"
      ],
      "properties": {
        "photo": {
          "type": "file",
          "x-amf-fileTypes": [
            "image/jpeg",
            "image/png"
          ],
          "minLength": 1,
          "maxLength": 307200
        }
      },
      "type": "object"
    }
  }
}
```

**Comment by gutee** [comment]
Oas apis support 'file' type, raml too, we can't restrict this as we don't know where it will be used. It's up to the user to translate this or not.

Also, there is nothing to translate this to, as contentEncoding facet is available since schema 07 only.

**Comment by postatum** [comment]
Hi @gutee . Thank you for your answer!

> Oas apis support 'file' type, raml too

Right. OAS 2.0 and RAML have type "file". OAS 3.0 doesn't. But that's not my point.

> we can't restrict this as we don't know where it will be used

To me it seems like a method `toJsonSchema` would be used to produce JSON Schema. It has a `JsonSchema` in its name but produces an invalid JSON Schema representation of a file.

> Also, there is nothing to translate this to, as contentEncoding facet is available since schema 07 only.

My bad. Draft 04 had [binaryEncoding](https://json-schema.org/draft-04/json-schema-hypermedia.html#rfc.section.4.3.1.1) though.

**Comment by gutee** [comment]
I understand, but as we can't assume that translation is correct, we can't do that. Maybe the name is misleading and we should change that. But right now that is how users use and understand it and we will not change it. Thanks for the clarification though!

**Comment by postatum** [comment]
Got it. Thank you too.
