### ISSUE TITLE
Getting values of annotation fields

### ISSUE THREAD

**Issue by postatum** [aml-org/amf#543]
Considering RAML example below, how do I get values of `Cat.ramltopojo.plugins[0].name` and other items' properties?

```raml
#%RAML 1.0

annotationTypes:
  ramltopojo:
    type: object
    properties:
      plugins:
        type: array
        items:
          type: object
          properties:
            name: string
            arguments: string

types:
  Cat:
    type: object
    (ramltopojo):
      plugins:
        - name: firstPlugin
          arguments: something
        - name: secondPlugin
          arguments: somethingElse
    properties:
      name: string
```

**Comment by gutee** [comment]
Hi @postatum, to answer your question:

Once you get to the Cat type (in the declares property of the document), this NodeShape will have a 'customDomainProperties' property, which will have the annotation ramltopojo. This annotation will have an 'extension' property with the current value, which is a DataNode (ObjectNode, ArrayNode, ScalarNode).

You could use 'properties' in the first ObjectNode, which will give you a map which has the 'plugins' prop with an ArrayNode associated, which has a 'members' property with two ObjectNodes.

**Comment by postatum** [comment]
Thanks @gutee !
