### ISSUE TITLE
Property "examples" is always an empty list

### ISSUE THREAD

**Issue by postatum** [aml-org/amf#546]
With amf-client-js@3.3.0 and apparently Java version as well.

Consider this code [1] which outputs this [2]. Note how `examples` is always an empty list.

According to issue reported in webapi-parser (https://github.com/raml-org/webapi-parser/issues/34), this happens to examples on other nodes and in Java.

[1]
```js
const amf = require('amf-client-js')

const ramlStr = `
  #%RAML 1.0
  title: Test API
  version: 1.0
  baseUri: https://test.com

  /test/{id}_{anotherId}:
    uriParameters:
      id:
        type: string
        examples:
          simple: ABC123
          complex: QWEQWEQWEQWE
      anotherId:
        type: string
        example: VSDJ1424
`

async function main () {
  await amf.AMF.init()
  const model = await amf.AMF.raml10Parser().parseStringAsync(ramlStr)
  model.encodes.endPoints[0].parameters.forEach(param => {
    console.log(param.name.value(), param.examples)
  })
}

main()
```

[2]
```
id []
anotherId []
```

**Comment by gutee** [comment]
Examples in raml are part of the schema property in amf model, they are accessed like this:

encodes.endPoints[0].parameters[0].schema.examples
