### ISSUE TITLE
How to figure out a concrete implementation of Shape?

### ISSUE THREAD

**Issue by postatum** [aml-org/amf#552]
Hi.

Is there a way to figure out a concrete implementation of `Shape` when a method's return type is `Shape`? 
E.g. `Payload.schema()` method/property returns `Shape`.

This question comes from https://github.com/raml-org/webapi-parser/issues/38#issuecomment-526109933

**Comment by gutee** [comment]
You can use an `instanceof` in js. In amf bundle the classes of the specific shapes are exposed, this means that if you import, for example NodeShape, you are able to use the class like this `shape instanceof NodeShape`.

**Comment by postatum** [comment]
Nice, thanks!
