### ISSUE TITLE
minimum, maximum, minLength, maxLength are 0 when not defined

### ISSUE THREAD

**Issue by postatum** [aml-org/amf#562]
Using amf-client-js@3.5.4, consider this code [1].

I think `minimum` and `maximum` should not return `0`, but `null` or `undefined`.
Getting value `0` makes it impossible to guess whether user specified `minimum: 0` or didn't specify `minimum` at all.

Happens for both `number`, `integer` and string `min/maxLength`.

```js
const amf = require('amf-client-js')


const ramlStr = `
#%RAML 1.0
baseUri: https://{myId}.hello:1234
baseUriParameters:
  myId:
    type: number
`

async function main () {
  await amf.AMF.init()

  const model = await amf.AMF.raml10Parser().parseStringAsync(ramlStr)
  const myId = model.encodes.servers[0].variables[0]
  console.log(myId.schema.minimum.value())
  console.log(myId.schema.maximum.value())
}

main()
```

```sh
$ node raml10.js 
0
0
```

**Comment by gutee** [comment]
Hi, this is because you are using the value() method which will give you a default value if none is found. You can use the option() method to get an Option, or the isNull/nonNull methods to check this.

**Comment by postatum** [comment]
Amazing. Thank you!
