### ISSUE TITLE
Issue when translating JSON schema array items to RAML

### ISSUE THREAD

**Issue by jstoiko** [aml-org/amf#564]
A JSON Schema can define an array with items that can be of multiple possible types. The way to do that in JSON Schema is to declare an array of types as the value of "items", e.g. `"items": [(...)]`. 

The screenshot below is an example.

<img width="1298" alt="Screen Shot 2019-11-01 at 17 35 07" src="https://user-images.githubusercontent.com/9660342/68162361-b271be80-ff0c-11e9-82d5-476b092f71e4.png">

Currently AMF does not translate this shape to RAML Datatype but it should as the RAML equivalent would a union of types. See examples below.

```raml
types:
  ObjA:
    properties:
      a1: string
      a2: integer
  ObjB:
    properties:
      b1: string
      b2: integer
  ObjC:
    properties:
      c1: string
      c2: integer
  MyObj:
    properties:
      some_property:
        items: ObjA | ObjB | ObjC
```

This is related to https://github.com/raml-org/ramldt2jsonschema/issues/111

**Comment by gutee** [comment]
Hi Jonathan, according to https://tools.ietf.org/html/draft-fge-json-schema-validation-00#section-8.2.3.2 that is not the behaviour of the items as an array, it is a tuple style behaviour. With this meaning, the json schema you are exposing can't be rendered in raml types, and the unions example don't have the same meaning as the json schema.
