### ISSUE TITLE
How to get a list of required properties of RAML DT (NodeShape)?

### ISSUE THREAD

**Issue by postatum** [aml-org/amf#566]
I define a RAML Data Type in a RAML document/lib and parse it. Then I access that defined datatype using amf model and get a `NodeShape`.
But how do I check which properties (`PropertyShape`) of `NodeShape` are required?

**Comment by gutee** [comment]
Hi, when the propertyShape is required property minCount will be 1, else it will be 0.

**Comment by postatum** [comment]
> Hi, when the propertyShape is required property minCount will be 1, else it will be 0.

And is there a name to list required fields' names?

**Comment by gutee** [comment]
There is not, you will have to traverse the list to check which are required

**Comment by postatum** [comment]
> There is not, you will have to traverse the list to check which are required

And how do I figure out which field is required? `NodeShape` properties are `PropertyShape` which have a `range` of `Shape` subclasses. None of those seem to have fields similar to `required`.

**Comment by gutee** [comment]
Node shape has properties which are PropertyShape instances. PropertyShapes have a minCount property. When the value of this property is 1, it is required, when it is 0, it is not required.

**Comment by postatum** [comment]
Oh I got it. Sorry, misunderstood you the first time. Thanks!

**Comment by postatum** [comment]
@gutee I don't want to open a new issue to ask another API question, so please help me with this one.
Is there a way to get [RAML 0.8 "repeat" property](https://github.com/raml-org/raml-spec/blob/master/versions/raml-08/raml-08.md#repeat) value?

E.g. I have a `NodeShape` with `PropertyShape`s in it all of which are `ScalarShape`s. And the document looks like this [1]. How do I figure out if property is `repeat: true` or `repeat: false`?

[1]
```raml
#%RAML 0.8
title: simple storage API
version: 1
baseUri: https://{destinationBucket}.s3.asd.com
/:
  post:
    body:
      application/x-www-form-urlencoded:
        formParameters:
          qwe:
            type: string
            repeat: false
          abc:
            type: string
            repeat: true
```

**Comment by gutee** [comment]
Hi, 'repeat' property means that property will be an ArrayShape (the range of the PropertyShape)
