### ISSUE TITLE
Resolving large files never finishes

### ISSUE THREAD

**Issue by postatum** [aml-org/amf#567]
Consider this issue https://github.com/raml-org/webapi-parser/issues/56.

The code I used to test:
```js
const amf = require('amf-client-js')

async function main () {
  const hrstart = process.hrtime();

  await amf.AMF.init()
  const model = await amf.AMF.raml10Parser().parseFileAsync(
    `file:///Downloads/commercetools-api-reference/api.raml`)
  console.log('parsed', process.hrtime(hrstart))

  const resolved = await amf.AMF.resolveRaml10(model)
  console.log('resolved', process.hrtime(hrstart))
}

main()
```

On my machine parsing takes about 15 seconds but resolution works for 10 minutes and does not finish.

**Comment by tomsfernandez** [comment]
Hi @postatum. I have tested this API in AMFs most recent version (4.1.2 JS) and it has improved dramatically since the time you tested it. The times were:
- Parsing: 7 seconds
- Resolution: 155 seconds (2 minutes 30 seconds)

The test was conducted with Node 13.1.0.

**Comment by tomsfernandez** [comment]
I'm closing this issue as the time it takes to resolve the API has improved a lot given it's complexity (it is a very big and complex API with lots of resource types to be applied)
