### ISSUE TITLE
Inconsistent OAS20 generated from RAML DataType

### ISSUE THREAD

**Issue by postatum** [aml-org/amf#571]
Using amf-client-js@4.0.2.

I've ran this code [0] and got different OAS 20 structure depending on where `!include` was used in RAML.

When it's used in array `items` [1], it gets translated to OAS as `"$ref": "inventoryObject.raml"` [2]. 
When it's used in `type` [3], it gets translated to OAS as `"$ref": "#/definitions/type"` [4].

PS. After resolution produced OAS is correct in both cases, but before resolution it isn't.

[0]
```js
const amf = require('amf-client-js')

async function main () {
  await amf.AMF.init()
  const model = await amf.AMF.raml10Parser().parseFileAsync(`file:///somewhere/api.raml`)
  const gen = await amf.AMF.oas20Generator().generateString(model)
  console.log(gen)
}

main()
```
[1]
```raml
#%RAML 1.0 DataType
description: Price Request
properties:
  inventoryObject:
    type: array
    items: !include inventoryObject.raml
```
[2]
```json
{
  "x-amf-fragmentType": "2.0 DataType",
  "description": "Price Request",
  "type": "object",
  "required": [
    "inventoryObject"
  ],
  "properties": {
    "inventoryObject": {
      "type": "array",
      "items": {
        "$ref": "inventoryObject.raml"
      }
    }
  }
}
```
[3]
```raml
#%RAML 1.0 DataType
description: Price Request
properties:
  inventoryObject:
    type: !include inventoryObject.raml

```
[4]
```json
{
  "x-amf-fragmentType": "2.0 DataType",
  "description": "Price Request",
  "type": "object",
  "required": [
    "inventoryObject"
  ],
  "properties": {
    "inventoryObject": {
      "type": "object",
      "x-amf-merge": [
        {
          "$ref": "#/definitions/type"
        }
      ]
    }
  }
}
```

**Comment by BBartosz** [comment]
Cant we parse object type same way we parse array item type?

**Comment by BBartosz** [comment]
@postatum could you point me direction where I should look for parsing logic?

**Comment by tomsfernandez** [comment]
Hi @postatum. This difference you are seeing is the expected.
[1] and [2]. The produced json schema also has an array and items field similar to the RAML datatype.
[3] and [4]: I suspect this is the one that brings confusion. As there is no inheritance in JsonSchema then the type can't be expressed as the RAML inheritance in [3]. That is why it is an object with an annotation making explicit that [4] comes from a parsed inheritance.

By the way you are comparing the output of type different RAML Types, one being an Array and the other an Object. I can't see the point you are trying to make by comparing both.

**Comment by postatum** [comment]
Hi @tomsfernandez. Thank you for the response.

My point is - I expected both includes to produce a similar ref. Either `"$ref": "inventoryObject.raml"` or `"$ref": "#/definitions/type"`. I can't recall why exactly I needed it though.
