### ISSUE TITLE
Exception when trying to clear items in tags() while parsing RAML files in Java

### ISSUE THREAD

**Issue by Serdarrr** [aml-org/amf#582]
Hi,

I'm using [web api parser](https://github.com/raml-org/webapi-parser) to generate RAML files from OpenApi 3 (using [springdoc](https://github.com/springdoc/springdoc-openapi)). I want to able to remove certain fields, I managed the remove few of them like server description and operation names. But while removing tags() using clear() method I am getting the following exception error.

This needed for the CMS I'm using and while validating the RAML file, it finds the amf prefixed variables invalid. It works without them.

**Error**
```js
Exception in thread "main" java.lang.Exception: Cannot find builder for object meta amf.plugins.domain.webapi.metamodel.TagModel$@6bf0219d
	at amf.core.remote.Platform.wrapFn(Platform.scala:98)
	at amf.core.remote.Platform.wrapFn$(Platform.scala:93)
	at amf.core.remote.JvmPlatform.wrapFn(JvmPlatform.scala:9)
```
**Scenario**

- Parsing OpenApi json document to WebApiDocument instance
- Encoding document to WebApi instance
- Editing existing endpoints in WebApi
- Mapping through endpoints and removing 

**Example Code**
```js
    public static void translateFromUrl(String url, String endPointName, boolean raml10) throws InterruptedException, ExecutionException {
        // Parse Swagger 3 document to WebApiDocument
        WebApiDocument doc = (WebApiDocument) Oas30.parse(url).get();

        // Filter out specific API endpoints of current endpoint list based on API path names
        if (!endPointName.isEmpty()) {
            // Get the API instance
            WebApi api = (WebApi) doc.encodes();

            // Removes amf prefixed fields
            // Field (amf-serverDescription), base url description
            List<Server> serverList = api.servers();
            serverList.get(0).description().remove();
            api.withServers(serverList);

            api.endPoints().forEach(endPoint -> endPoint.operations().forEach(operation -> {
                operation.name().remove(); // field displayName
                operation.tags().clear(); // field (amf-tags)
            }));

            // Create new endpoint list based on path that ends with endpoint name
            List<EndPoint> newList = api.endPoints().stream()
                    .filter(endPoint -> endPoint.relativePath().endsWith(endPointName)).collect(Collectors.toList());
            api.withEndPoints(newList);
        }

        String fpath = "file://api-endpoints.raml";
        if (raml10) {
            // Resolve parsed model
            WebApiBaseUnit resolved = Raml10.resolve(doc).get();
            // Generate RAML 1.0 file
            Raml10.generateFile(resolved, fpath).get();
        } else {
            // Resolve parsed model
            WebApiBaseUnit resolved = Raml08.resolve(doc).get();
            // Generate RAML 0.8 file
            Raml08.generateFile(resolved, fpath).get();
        }
    }
```

This could be the same issue as in #485

**Comment by AgustinBettati** [comment]
Hello @Cytor! First of all, i would encourage you use our issue template so that we have important details clarified beforehand. 
As of this case, it is a known issue which has been fixed in AMF version 4.1.2 in the following commit c9083ea0.
[Web api parser](https://github.com/raml-org/webapi-parser) is currently using version 4.0.3. Your alternatives are to use AMF directly using the updated version, or request to update the version from their side.
Feel free to leave a comment if you have any doubts.

**Comment by Serdarrr** [comment]
Hello @AgustinBettati, thank you I will use the template for the next time. Nice that this bug is fixed. It seems that I can also achieve the above code (web api parser) with AMF framework only? I was considering to switch to only AMF, instead of using the raml parser that relies on AMF.

**Comment by AgustinBettati** [comment]
Yes that is correct, you can take a look at [amf examples](https://github.com/mulesoft/amf-examples) as a guideline, and also look at how webapi parser is using AMF.

**Comment by Serdarrr** [comment]
@AgustinBettati You mentioned using an alternative by using AMF directly, did you mean switch to AMF or use latest AMF maven dependency with raml webapi-parser? I tried adding amf_client dependency but no luck (getting an error no method found..)

**Comment by AgustinBettati** [comment]
What i mean by the first alternative is to replace raml webapi-parser for amf directly, but this will surely require some changes in your code base as they do not expose the same interfaces (even though they seem fairly similar).

**Comment by Serdarrr** [comment]
Thank you for clarifying.
