### ISSUE TITLE
OAS 3 renderer outputs swagger 2.0 for RAML 1.0 Library

### ISSUE THREAD

**Issue by postatum** [aml-org/amf#585]
Using amf-client-js@4.0.5

Consider the code [1] and the output [2]. 
When converting regular RAML API (`#%RAML 1.0` header, not a Library), output OAS version is correct - `"openapi": "3.0.0"`.

[1]
```js
const amf = require('amf-client-js')

const ramlStr = `
#%RAML 1.0 Library
types:
  UserName:
    type: string
`

async function main () {
  await amf.AMF.init()
  const model = await amf.AMF.raml10Parser().parseStringAsync(ramlStr)
  const ren = new amf.Oas30Renderer()
  console.log(await ren.generateString(model))
}

main()
```
[2]
```json
{
  "swagger": "2.0",
  "schemas": {
    "UserName": {
      "type": "string"
    }
  }
}
```

**Comment by tomsfernandez** [comment]
Hi @postatum. I could reproduce this problem and have created an internal ticket for the team to evaluate.
The internal ticket is: https://www.mulesoft.org/jira/browse/APIMF-2184

**Comment by tomsfernandez** [comment]
Hi @postatum. This issue has been fixed and will be available in the next AMF version. The commit is: d7b7c5a7. I'm closing this issue. Thanks for contributing.
