### ISSUE TITLE
Undocumented resolution behaviour change for OAS 2.0 and 3.0 in version 4.1.2

### ISSUE THREAD

**Issue by postatum** [aml-org/amf#596]
* **I'm submitting a ...**
  - [ ] bug report
  - [ ] question

* **What is the current behavior?**
OAS 2.0 and 3.0 resolution leaves definitions/components.

* **What is the expected behavior?**
OAS 2.0 and 3.0 resolution should move definitions from definitions/components to endpoints.

* **Please tell us about your environment:**
  
  - AMF Version: 4.1.2
  - AMF Distribution: JS

* **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, Gitter, etc)

Consider the code [1] and the input [2]. Also note what OAS resolution produces on version 4.1.1 [3] and 4.1.2 [4]. This is true for both OAS 2.0 `definitions` and OAS 3.0 `components/schemas`. Resolution behaviour did not change for RAML.

Did resolution behaviour change on 4.1.2? If so, please explain how exactly it changed. Thanks in advance!

[1]
index.js
```js
const amf = require('amf-client-js')

async function main () {
  await amf.AMF.init()
  const model = await amf.AMF.oas20Parser().parseFileAsync('file://api.json')
  const resolved = await amf.AMF.resolveOas20(model)
  const resolvedStr = await amf.AMF.oas20Generator().generateString(resolved)
  console.log(resolvedStr)
}

main()
```

[2]
api.json
```json
{
  "swagger": "2.0",
  "info": {
    "title": "API with Types",
    "version": ""
  },
  "paths": {
    "/users/{id}": {
      "get": {
        "responses": {
          "200": {
            "schema": {
              "$ref": "#/definitions/User"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "User": {
      "type": "object",
      "properties": {
        "firstName": {
          "type": "string"
        }
      },
      "required":[
        "firstName"
      ]
    }
  }
}
```

[3]
Resolved with 4.1.1
```json
{
  "swagger": "2.0",
  "info": {
    "title": "API with Types",
    "version": ""
  },
  "paths": {
    "/users/{id}": {
      "get": {
        "responses": {
          "200": {
            "schema": {
              "type": "object",
              "additionalProperties": true,
              "required": [
                "firstName"
              ],
              "properties": {
                "firstName": {
                  "type": "string"
                }
              }
            },
            "description": ""
          }
        }
      }
    }
  }
}
```

[4]
Resolved with 4.1.2
```json
{
  "swagger": "2.0",
  "info": {
    "title": "API with Types",
    "version": ""
  },
  "paths": {
    "/users/{id}": {
      "get": {
        "responses": {
          "200": {
            "schema": {
              "$ref": "#/definitions/User"
            },
            "description": ""
          }
        }
      }
    }
  },
  "definitions": {
    "User": {
      "type": "object",
      "additionalProperties": true,
      "required": [
        "firstName"
      ],
      "properties": {
        "firstName": {
          "type": "string"
        }
      }
    }
  }
}
```

**Comment by tomsfernandez** [comment]
Hi @postatum. We migrated to this "compact" emission because it is much more performant in cases with very big and complex apis. From 4.1.2 common refs are extracted to the declarations section.
I have updated the release notes of version 4.1.2 to reflect this change. Thanks for the heads up!

**Comment by postatum** [comment]
Hi @tomsfernandez. Thanks for being so responsive!

> Hi @postatum. We migrated to this "compact" emission because it is much more performant in cases with very big and complex apis. From 4.1.2 common refs are extracted to the declarations section.
> I have updated the release notes of version 4.1.2 to reflect this change. Thanks for the heads up!

I see.
What does resolution do to OAS now? Is there a way to see it change OAS2-3 document substantially? 
I need this to describe OAS resolution in `webapi-parser` docs and tests.

**Comment by tomsfernandez** [comment]
It is not a change in resolution. It only impacts the way OAS is emitted to an API

**Comment by postatum** [comment]
> It is not a change in resolution. It only impacts the way OAS is emitted to an API

Hi @tomsfernandez.

I don't mean to judge this optimization, I'm just trying to understand what "resolution" means now when applying it to OAS document.

I guess I'm missing something because to me it seems like it does affect resolution. I seems so because:

* Using AMF 4.1.1, if I simply parse an OAS doc with `definitions` and generate string from it the `definitions` property is present in the output string,
* Using AMF 4.1.1 when I resolve a parsed doc before generating a string, types from `definitions` are merged into endpoints (in other words - not present in the output string).
* On the other hand, using AMF 4.1.2, when I resolve a parsed doc and generate a string from it, output string still has `definitions` property.


I understand that internally a document may still become "resolved" when resolution happens and then it's optimized to using `definition` when emitting OAS string. But from users perspective it looks like resolution did not happen because the output does not look resolved.

Please help me understand what does "resolution" do to OAS documents now from users' perspective?

**Comment by tomsfernandez** [comment]
AMF api processing has 2 parts:
- **Parsing**: an API in RAML/OAS is scanned, analyzed and dumped into the AMF model (WebApi, Endpoint, Operation, Request, etc.). The resultant AMF model has undetected cycles, links (explicit references between requests and types for example) and unmerged traits and resource types in the case of RAML.
- **Resolution**: Here is where the AMF model is rearranged to solve those links (join references between types), merge endpoints and operations with resource types and traits, etc. This stage only applies to the AMF model and is independent as how the model is emitted. 

In this case the resolved AMF model is the same as in AMF 4.1.1. The only way to know if a model has been resolved is by inspecting the in memory model itself or it's jsonld graph representation. Model emission is **independent** of how the model is resolved or parsed as the same model can be expressed in a Spec in many ways.

**Comment by postatum** [comment]
Understood. Is there a way to opt out of the new optimized OAS emission? (Output spec the "old way")

**Comment by tomsfernandez** [comment]
Not at the moment. We don't have plans in the short term to expose the old OAS emission as the new one is much more efficient and solves several `$ref` problems we were having.

**Comment by postatum** [comment]
Hi @tomsfernandez :)

I got one more question. I was told that it's possible to use `SourceMap`s to somewhat resolve this issues. I was told it's possible to provide a sourcemap to control the generated output.

Can you confirm this? If so, how do I properly use `SourceMap`s?

**Comment by tomsfernandez** [comment]
Hi @postatum . Please open another issue  so that we can do the follow up in that thread.
