### ISSUE TITLE
RAML10 -> OAS30: Documentation incorrect

### ISSUE THREAD

**Issue by philipp-kaiser** [aml-org/amf#649]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] question
  - [ ] other

* **What is the current behavior?**

Raml documentation section is not translated correctly

Converting this simple RAML file:
```
#%RAML 1.0

title: Documentation
version: v1
documentation:
- title: First title
  content: First content
- title: Second title
  content: Second content
```

* **If the current behavior is a bug, please provide the minimal steps to reproduce with AMF code. Please don't upload AMF code mixed with yours.**

Java function to convert raml file to oas file:
```
public static void ramlToOasWithoutFix(final File raml, final File oas) throws Exception {
    AMF.init().get();
    final BaseUnit rawModel = new Raml10Parser().parseStringAsync(new String(Files.readAllBytes(raml.toPath()))).get();
    final BaseUnit resolvedModel = new Oas30Resolver().resolve(rawModel, ResolutionPipeline.COMPATIBILITY_PIPELINE());
    Files.write(oas.toPath(), new Oas30Renderer().generateString(resolvedModel).get().getBytes());
}
```

Output is:
```
{
  "openapi": "3.0.0",
  "info": {
    "title": "Documentation",
    "version": "v1"
  },
  "externalDocs": {
    "url": "http://",
    "description": "First content",
    "x-amf-title": "First title"
  },
  "x-amf-userDocumentation": [
    {
      "url": "http://",
      "content": "Second content",
      "title": "Second title"
    }
  ],
  "paths": {}
}
```

* **What is the expected behavior?**

Output should be:

```
{
  "openapi": "3.0.0",
  "info": {
    "title": "Documentation",
    "description": "<- insert here ->"
    "version": "v1"
  },
  "paths": {}
}
```

As there is nothing like documentation in OAS (only the external url), the complete section should be handled as description in the info block. To be honest, i'm not sure how multiple titles and descriptions should be handled best, maybe with CommonMark syntax.

* **Please tell us about your environment:**
  
  - AMF Version: 4.3.0
  - AMF Distribution: JVM
  - Operating System: Windows 10 64 bit

**Comment by nschejtman** [comment]
Hi @Kaiser1989, as you said there is no 1-to-1 mapping for this RAML feature in OAS 3.0. Our conversion does a "best effort" to preserve all the properties from the original model in the target spec. This "best effort" subjective to all adopters so unless you provide an argument we consider valid for changing this specific conversion we won't change it. 

Closing for now, feel free to reopen if you elaborate an argument for us to review
