### ISSUE TITLE
Unresolved reference when example has same filename as a type filename

### ISSUE THREAD

**Issue by dcrossleyau** [aml-org/amf#661]
* **I'm submitting a ...**
  - [*] bug report

* **What is the current behavior?**
If the filename of an example is the same as the filename of a parent schema type, then "Unresolved reference" violations occur.

* **What is the expected behavior?**
Happiness.

* **Please tell us about your environment:**
  
  - AMF Version: amf-client-js (v4.3.0)
  - AMF Distribution: JS 
  - Operating System: macOS
  - Link to your project: https://dev.folio.org/reference/api/

* **Other information**

We have many hundreds of RAML files. Those all do assess as valid using raml-js-parser-2 (v1.1.67). However when using amf-client-js (v4.3.0) many of them have violations.

It seems that when an example file has the same filename as the JSON Schema that defines it, then the violations occur.

I have devised a set files to demonstrate the problem.
Packaged in the archive [pets-20200923.tar.gz](https://github.com/aml-org/amf/files/5273656/pets-20200923.tar.gz)
There is output from the parsers in the file [report-20200923.txt](https://github.com/aml-org/amf/files/5273658/report-20200923.txt)

The schemas and examples have been verified with ajv.

Some observations:

A) pets-2 and pets-6 and pets-9 are successful. The filename of its example is not the same as that of its parent schema. They also indicate that there is no need to declare the referenced child schema in the RAML Types section.

B) pets-1 indicates that violations start to happen if the example filename is the same as the parent schema filename.

C) pets-5 indicates that when more child schema are referenced, then there are more violations. Also the sudden "file:" protocol is strange. Also that violation is looking for the parent schema in the examples directory.

A summary:

pets-1.raml
The parent schema has 1x $ref to a child schema. The example filename is the same as the parent schema.
pet-a.json has 1x $ref to period.json
type is not declared for period.json
examples/pet-a.json
One violation:
Violation - Unresolved reference 'period.json'

pets-2.raml
The parent schema has 1x $ref to a child schema. The example filename is different to the parent schema.
pet-a.json has 1x $ref to period.json
type is not declared for period.json
examples/pet-a-renamed.json
Zero violations

pets-3.raml
The parent schema has 1x $ref to a child schema. The example filename is the same as the parent schema.
pet-a.json has 1x $ref to period.json
type is declared for period.json
examples/pet-a.json
Zero violations

pets-4.raml
The parent schema has 2x $ref to the same child schema. The example filename is the same as the parent schema.
pet-b.json has 2x $ref to period.json
type is not declared in raml for period.json
examples/pet-b.json
Zero violations

pets-5.raml
The parent schema has 2x $ref to the same child schema, and 1x $ref to another child schema. The example filename is the same as the parent schema.
pet-c.json has 2x $ref to period.json, plus 1x $ref to uuid.json
type is not declared in raml for period.json
type is not declared in raml or uuid.json
examples/pet-c.json
Three violations
Note also the strange pathname looking for the schema in the "examples" directory.
Violation - Unresolved reference 'period.json'
Violation - Unresolved reference 'file://test-pets/examples/period.json'
Violation - Unresolved reference 'uuid.json'

pets-6.raml
The parent schema has 2x $ref to the same child schema, and 1x $ref to another child schema. The example filename is different to the parent schema.
pet-c.json has 2x $ref to period.json, plus 1x $ref to uuid.json
type is not declared in raml for period.json
type is not declared in raml for uuid.json
examples/pet-c-renamed.json
Zero violations

pets-7.raml
The parent schema has 2x $ref to the same child schema, and 1x $ref to another child schema. The example filename is the same as the parent schema.
pet-c.json has 2x $ref to period.json, plus 1x $ref to uuid.json
type is declared in raml for period.json
type is not declared in raml for uuid.json
examples/pet-c.json
Two violations
Violation - Unresolved reference 'file://test-pets/examples/period.json'
Violation - Unresolved reference 'uuid.json'

pets-8.raml
The parent schema has 2x $ref to the same child schema, and 1x $ref to another child schema. The example filename is the same as the parent schema.
pet-c.json has 2x $ref to period.json, plus 1x $ref to uuid.json
type is declared in raml for period.json
type is declared in raml for uuid.json
examples/pet-c.json
Two violations
Violation - Unresolved reference 'file://test-pets/examples/period.json'
Violation - Unresolved reference 'uuid.json'

pets-9.raml
The parent schema has 2x $ref to the same child schema, and 1x $ref to another child schema. The example filename is different to the parent schema.
pet-c.json has 2x $ref to period.json, plus 1x $ref to uuid.json
type is declared in raml for period.json
type is declared in raml for uuid.json
examples/pet-c-renamed.json
Zero violations

**Comment by nschejtman** [comment]
Hi @dcrossleyau, we confirm this is a bug. Tracking in our internal Jira (APIMF-2559). Once that's fixed we'll update this issue

**Comment by arielmirra** [comment]
Hi @dcrossleyau! This issue has been resolved in the latest release of AMF 4.4.0 so I'm closing it, Thank you!

**Comment by dcrossleyau** [comment]
Thanks. Verified with our set of RAML files. That reduced the number of files which indicated "violations" from 75 to 25. Nice.
