### ISSUE TITLE
Cannot retrieve RAML annotations applied to Library

### ISSUE THREAD

**Issue by kdubb** [aml-org/amf#779]
Your issue may already be reported! Please search on Github issues before creating one.

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] question
  - [ ] other

* **What is the current behavior?**

RAML `Library` level annotations are lost or inaccessible after parsing. `API`'s add the annotation(s) to the root encoded object in `EncodesModel.encode`.

* **If the current behavior is a bug, please provide the minimal steps to reproduce with AMF code. Please don't upload AMF code mixed with yours.**
Given the following RAML library example...

```yaml
#%RAML 1.0 Library
uses:
  gen: ../generator.raml

(gen.javaModelPackage): io.test.lib

types:

  Test:
    type: object
    properties:
      value: string
```

There is no way to retrieve the `javaModelPackage` annotation. On an `API` (aka `Document`) there's and `EncodesModel` trait and the annotation is applied to the root of the encoded model. With a `Library` there is no way to retrieve the top level annotation.

Note that `generator.raml` just defines some annotations for generating code.

* **What is the expected behavior?**

It should be possible to retrieve the annotations from `Library` & `Fragment` modules as well.

* **What is the motivation/use case for changing the behavior? (for feature requests)**

* **Please tell us about your environment:**
  
  - AMF Version: 4.5.1
  - AMF Distribution: JVM or JS 
  - Operating System: macOS
  - Link to your project:

* **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, Gitter, etc)

**Comment by kdubb** [comment]
A "proper" solution might be adding a `customDomainProperties` to `BaseUnit` where top-level annotations are available for all RAML module types.

**Comment by looseale** [comment]
Hi @kdubb . 
You are right, the spec allows that function and currently the annotations in the root level are missing because they don't have a place in the current library model (Module).
I created the internal ticket https://www.mulesoft.org/jira/browse/APIMF-2769 to check this. We will keep you informed of any news.

**Comment by kdubb** [comment]
I'm willing to contribute a PR if you can point me in the right direction. We're moving from the old RAML parser and this is a blocking issue for us.

**Comment by kdubb** [comment]
@looseale Also, it's worth noting that although the 3.0 OpenAPI spec only allow "extensions" on certain elements... all the notable parser implementations seem to allow extension nearly everywhere; specifically on document root and schema items.

**Comment by kdubb** [comment]
@looseale Any thoughts on when this might be fixed or how I can help get this started?

**Comment by tomsfernandez** [comment]
Hi @kdubb. This issue was resolved in https://github.com/aml-org/amf/pull/817. It will be available on the release of AMF's next version next week.

Thanks for raising the issue.
With the merged PR I'm closing the issue.
