### ISSUE TITLE
SPARQL validation in JS results in 'not assigned' error

### ISSUE THREAD

**Issue by bredmond-sf** [aml-org/amf#790]
Your issue may already be reported! Please search on Github issues before creating one.

* **I'm submitting a ...**
  - [ x ] bug report
  - [ ] feature request
  - [ ] question
  - [ ] other

* **What is the current behavior?**

When trying use the following query with https://github.com/SalesforceCommerceCloud/raml-toolkit/blob/master/testResources/raml/mercury/mercury.raml (or other RAMLs)

```yaml
  unique-display-names:
    message: Operation displayName must be unique within an API
    targetClass: apiContract.WebAPI
    query: |
      SELECT ?this (?operation1 as ?value)
      WHERE {
        ?operation1 core:name ?name1 .
        ?operation1 rdf:type  apiContract:Operation .
        ?operation2 core:name ?name2 .
        ?operation2 rdf:type  apiContract:Operation .
        FILTER (?operation1 != ?operation2 && lcase(str(?name1)) = lcase(str(?name2)))
      }
```

I receive ```Variables '?this' are used in the projection result, but are not assigned.```

This does not happen in the JVM version.

* **If the current behavior is a bug, please provide the minimal steps to reproduce with AMF code. Please don't upload AMF code mixed with yours.**

See above.

* **What is the expected behavior?**

The validation should pass without error.

* **What is the motivation/use case for changing the behavior? (for feature requests)**

* **Please tell us about your environment:**
  
  - AMF Version: 4.5.1
  - AMF Distribution: JS, node v12.15.0
  - Operating System: Mac OS Catalina
  - Link to your project: https://github.com/SalesforceCommerceCloud/raml-toolkit

* **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, Gitter, etc)

Opening this was requested by @looseale

**Comment by looseale** [comment]
Hi.
Using the validation like this should work in JS and JVM:
```  unique-display-names:
    message: Operation displayName must be unique within an API
    targetClass: apiContract.Operation
    query: |
      SELECT ?this ?value
      WHERE {
        ?this core:name ?value .
        ?this rdf:type  apiContract:Operation .
        ?operation2 core:name ?name2 .
        ?operation2 rdf:type  apiContract:Operation .
        FILTER (?this != ?operation2 && lcase(str(?value)) = lcase(str(?name2)))
      }
```

We will try to add an "auto-binding" of `?this` in JS like is happening in JVM and create some documentation about making queries in the near future.
