### ISSUE TITLE
Subtypes not always being rendered in converted OAS spec

### ISSUE THREAD

**Issue by jsantanasf** [aml-org/amf#810]
Your issue may already be reported! Please search on Github issues before creating one.

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] question
  - [ ] other

* **What is the current behavior?**
I have a RAML spec that relies on being able to have object inheritance for some of the types. For example, I have a generic `AttributeDefinition` with subtypes of `ItemIdentifierAttributeDefinition`, `DataAttributeDefinition`, and `LocalizedAttributeDefinition`. When downloading the RAML spec, this all looks OK, as this reflects what we actually provide through Design Center. However, when I download the generated OAS file, it only contains the definition for `AttributeDefinition` and none of its subtypes. According to the support team, it's because these subtypes aren't explicitly referenced in the spec. Adding them as a workaround works, but we don't want to expose a separate fake endpoint to get this working.

* **If the current behavior is a bug, please provide the minimal steps to reproduce with AMF code. Please don't upload AMF code mixed with yours.**

* **What is the expected behavior?**

* **What is the motivation/use case for changing the behavior? (for feature requests)**

* **Please tell us about your environment:**
  
  - AMF Version: 4.6.0
  - AMF Distribution: JVM
  - Operating System: Mac OS
  - Link to your project: Not external

* **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, Gitter, etc)

**Comment by tomsfernandez** [comment]
Linking to Jira issue: https://www.mulesoft.org/jira/browse/APIMF-2853

**Comment by jsantanasf** [comment]
Even though I mentioned the workaround works, I didn't look at the result close enough. The types get added to the resulting OAS spec, but still don't have any hierarchy information (e.g. `AttributeDefinition` doesn't mention `ItemIdentifierAttributeDefinition` as a subType, and vice versa).

**Comment by tomsfernandez** [comment]
Hi! @jsantanasf. That is the expected behaviour as OAS is based in JSON Schema and that spec doesn't have the concept of inheritance.

**Comment by tomsfernandez** [comment]
I'm closing this issue as this is AMF's expected behaviour and we won't be pursuing any enhancements to this feature yet.

**Comment by jsantanasf** [comment]
@tomsfernandez I'm confused...both OAS 2.0 and 3.0 have support for discriminators, which are there to provide polymorphism. Is there something I'm missing?

**Comment by nschejtman** [comment]
Hi @jsantanasf. Reviewed your case, I'll try to explain.

Technically polymorphism does not exist in any API spec. Polymorphism is a characteristic of the type system of the programming language implementing that API, which it might or might not have. In fact, types in RAML/OAS are not even actual types but schemas. API specs provide discriminators to support polymorphism in API implementations. How the API implementation chooses to use the discriminator information is a runtime concern. The RAML spec actually says it explicitly [here](https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#using-discriminator).

This is why when transforming RAML to OAS, we cannot tell whenever you reference a parent type if you are trying to reference that specific parent type or reference polymorphically any of the children types. What makes matters worse is that OAS doest not have a direct mapping for RAML inheritance. There are other mechanisms to achieve similar results in OAS, but these require us to make that decision (reference parent or any of its children) which unfortunately we cannot.

Hope this clears your confusion!
