### ISSUE TITLE
Id of request parameter nodes not unique

### ISSUE THREAD

**Issue by kdubb** [aml-org/amf#830]
Your issue may already be reported! Please search on Github issues before creating one.

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] question
  - [ ] other

* **What is the current behavior?**

Schema ids for RAML method queryParameters & headers are not unique.

* **If the current behavior is a bug, please provide the minimal steps to reproduce with AMF code. Please don't upload AMF code mixed with yours.**

Given the following snippet of RAML:
```raml

/tests/{type}:
  uriParameters:
    type:
      enum: [all,limited]
  get:
    displayName: fetchTest
    queryParameters:
      type:
        enum: [all,limited]
    headers:
      type:
        enum: [all,limited]
    responses:
      200:
        body:
          type: object

```

The type nodes for the parameters are generated as:

uriParameters:
file:///test.raml#/web-api/end-points/%2Ftests%2F%7Btype%7D/parameter/path/type
uriParameters.schema():
file:///test.raml#/web-api/end-points/%2Ftests%2F%7Btype%7D/parameter/default-binding/type/scalar/schema

queryParameters:
file:///test.raml#/web-api/end-points/%2Ftests%2F%7Btype%7D/get/request/parameter/query/type
queryParameters.schema():
file:///test.raml#/web-api/end-points/%2Ftests%2F%7Btype%7D/get/request/parameter/default-binding/type/scalar/schema

headers:
file:///test.raml#/web-api/end-points/%2Ftests%2F%7Btype%7D/get/request/parameter/header/type
headers.schema():
file:///test.raml#/web-api/end-points/%2Ftests%2F%7Btype%7D/get/request/parameter/default-binding/type/scalar/schema

* **What is the expected behavior?**

Each of the schema ids should be unique within the entire model.

* **What is the motivation/use case for changing the behavior? (for feature requests)**

Our generator is using the node id for caching & other type generation tasks and this causes conflicts.

* **Please tell us about your environment:**
  
  - AMF Version: 4.7.0-SNAPSHOT
  - AMF Distribution: JVM
  - Operating System: macOS
  - Link to your project:

* **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, Gitter, etc)

**Comment by tomsfernandez** [comment]
Hi @kdubb. I could replicate this using an RC for the upcoming release artifact. I created a bug in our internal issue system to track this: https://www.mulesoft.org/jira/browse/APIMF-2876. I wrote this here to link our internal ticket with Github.

All updates on this issue will be communicated through this channel (the Github issue).
Thanks!

**Comment by gutee** [comment]
Old issue. Closing.
