### ISSUE TITLE
RAML pattern properties are populated in NodeShape.properties

### ISSUE THREAD

**Issue by kdubb** [aml-org/amf#870]
Your issue may already be reported! Please search on Github issues before creating one.

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] question
  - [ ] other

* **What is the current behavior?**

Pattern properties defined in RAML are populated in `NodeShape.properties()`.

* **If the current behavior is a bug, please provide the minimal steps to reproduce with AMF code. Please don't upload AMF code mixed with yours.**

The following RAML produces a `NodeShape` for each of the types, Regex1 & Regex2, with a `properties()` that has a property with the pattern for a name.

```raml

Regex1:
  type: object
  properties:
    /test*/: string

Regex2:
  type: object
  properties:
    //: string

```

* **What is the expected behavior?**

Pattern properties should be populated in `additionalPropertiesSchema()` or similar.

* **What is the motivation/use case for changing the behavior? (for feature requests)**

* **Please tell us about your environment:**
  
  - AMF Version: 4.7.0
  - AMF Distribution: JVM
  - Operating System: macOS
  - Link to your project: https://github.com/outfoxx/sunday-generator

* **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, Gitter, etc)

**Comment by AgustinBettati** [comment]
Hello @kdubb!
The behavior your are describing is expected. Pattern properties are stored within `properties(): Seq[PropertyShape]`, taking into account that an additional field `PropertyShape.pattternName()` is present with the corresponding regular expression as a value.
I will close this issue but feel free to leave a comment if you have any doubts.
