### ISSUE TITLE
Missing `operationId` in the typpings for the `Operation`

### ISSUE THREAD

**Issue by jarrodek** [aml-org/amf#891]
* **I'm submitting a bug report**

* **What is the expected behavior?**
The `operationId` is defined in the typppings for the `Operation` object.

* **Please tell us about your environment:**
  
  - AMF Version: 4.7.1
  - AMF Distribution: JS 
  - Operating System: n/a
  - Link to your project: n/a

**Comment by tomsfernandez** [comment]
Hi @jarrodek. We have automated typing generation for AMF so know typings should be updated as we update the Scala interface.

https://github.com/aml-org/amf/blob/6f8b61c35758538791a0ee627588df23a5cdf98e/amf-client/js/typings/amf-client-js.d.ts#L1907 shows that the `operationId` is know part of the `Operation` object.

I'm closing this issue. Thanks for creating it.

PR: https://github.com/aml-org/amf/pull/906

**Comment by tomsfernandez** [comment]
Hi @jarrodek. We have had to rollback this change. Re-opening the issue.

**Comment by tomsfernandez** [comment]
Closing as it is present in AMF 5.0.0 and AMF 5.0.1
