### ISSUE TITLE
Setting additionalProperties is not properly reflected in "closed" property when using imported types

### ISSUE THREAD

**Issue by wjhsf** [aml-org/amf#902]
* **I'm submitting a ...**
  - [x] bug report

* **What is the current behavior?**
When parsing a RAML file with a type that has `additionalProperties: false`, the AMF model has `closed: true`. However, when that type is imported into a separate file and used, the AMF model incorrectly reports `closed: false`. The aliased type has a `linkTarget` that models the original type, which does correctly report `closed: true`.

* **If the current behavior is a bug, please provide the minimal steps to reproduce with AMF code. Please don't upload AMF code mixed with yours.**
See [this gist](https://gist.github.com/wjhsf/60198f3c097e7b50768a5377039fd091).

* **What is the expected behavior?**
The aliased type should correctly report `closed: true`.

* **Please tell us about your environment:**
  
  - AMF Version: 4.7.2
  - AMF Distribution: JS
  - Operating System: macOS Big Sur
  - Link to your project: The gist above is a minimal reproduction. I originally noticed this when parsing RAML files for the [Commerce SDK](https://github.com/SalesforceCommerceCloud/commerce-sdk), using the [RAML Toolkit](https://github.com/SalesforceCommerceCloud/raml-toolkit).

**Comment by nschejtman** [comment]
Hi @wjhsf, can you provide an example API where this occurs? Tried reproducing this but I'm getting the `closed:true` as expected

**Comment by wjhsf** [comment]
[This gist](https://gist.github.com/wjhsf/60198f3c097e7b50768a5377039fd091) has a minimal reproduction. When I run it (node v12.22.1 on macOS 11.2.3), I see this output:
```
Target ClosedObject closed? false
Linked NoPropertiesAllowed closed? true
```

Here's an [example API](https://github.com/SalesforceCommerceCloud/commerce-sdk/blob/master/apis/checkout/orders/orders.raml) where this occurs. I originally encountered this when building the [Commerce SDK](https://github.com/SalesforceCommerceCloud/commerce-sdk), with these steps:
1. Clone the repo
2. `npm ci`
3. `npm run clean && npm run renderTemplates`
4. Open `./renderedTemplates/checkout/orders/orders.ts`
5. Lines 92-101 should have the following:
```ts
export type ClosedObject = {
} & { [key: string]: any }

export type OpenObject = {
} & { [key: string]: any }

export type NoPropertiesAllowed = {
}
export type SpecifiedPropertiesAllowed = {
} & { [key: string]: any }
```

The expected output is that the type definition of `ClosedObject` matches that of `NoPropertiesAllowed`, i.e. simply `{}`.

**Comment by nschejtman** [comment]
Not sure how your code generator works but I'm taking a look at some types you defined in the `apis/checkout/orders/orders.raml` API and they seem to be OK. For example `DataTypes.OrderUpdateRequest` that extends `CommerceCloudStandards.OpenObject` is `closed: false` while `DataTypes.OrderConfirmationStatusUpdateRequest` that extends `CommerceCloudStandards.ClosedObject` is `closed: true`. Can you elaborate a reduced case to reproduce the error?

**Comment by nschejtman** [comment]
Just seen your minimal example. This is the expected behavior.

When you do `.value()` on a BoolField (like `closed`) which is not defined it returns `false` by default. You can call `.option` instead of `.value()` which returns `boolean | undefined`.

In your case the `.closed` field is not defined for your link but it is defined for your link target, so that is why you see that difference.

**Comment by nschejtman** [comment]
Closing the issue as it is the expected behavior
