### ISSUE TITLE
RAML Overlays replace all resources in overlaid API

### ISSUE THREAD

**Issue by kdubb** [aml-org/amf#962]
* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] question
  - [ ] other

* **What is the current behavior?**

When using an Overlay, if it attempts to overlay any resource from the overlaid document, all resources that are not overlaid are missing from the final document.

Given the RAML examples below, once parsed the only defined end point in the loaded API is `/test/{id}`. All the other resources are missing.

**_Also_**, the single defined `/test/{id}` end point is not merged with the original definition.  The endpoint will only have the properties defined in the overlay and none of the properties from the overlaid document.

Using this simple API:
```raml
#%RAML 1.0
title: Test API
baseUri: http://example.com
mediaType: application/json

/tests:
  get:
    displayName: listTests
    responses:
      200:
        body:
          type: string[]

/tests/{id}:
  get:
    displayName: fetchTest
    responses:
      200:
        body:
          type: string

/others:
  get:
    displayName: listOthers

  /{id}:
    get:
      displayName: fetchOther
      body:
        type: string
```

Using this overlay (which tries to apply an annotation):
```raml
#%RAML 1.0 Overlay
extends: test.raml

annotationTypes:
  test-ann: boolean

/tests/{id}:
  get:
    (test-ann): true
```

* **What is the expected behavior?**

Resources are overlaid according to the RAML spec. Any non-overlaid resources should remain in the document untouched. 

Also, resources should have their properties merged (some might even say "overlaid") with the definition from the original document.

* **Please tell us about your environment:**
  
  - AMF Version: 4.7.3
  - AMF Distribution: JVM
  - Operating System: macOS
  - Link to your project: http://outfoxx.github.io/sunday

**Comment by tomsfernandez** [comment]
Hi @kdubb. Can you specify how you are parsing the Overlay?

**Comment by kdubb** [comment]
@tomsfernandez  Here is the function:

https://github.com/outfoxx/sunday-generator/blob/f252cd5285d7f504e777661429085480f2cb586c/generator/src/main/kotlin/io/outfoxx/sunday/generator/parse.kt#L77

Excerpted for history's sake:
```kotlin

fun process(uri: URI): ProcessResult {

  AMF.init().get()

  val environment = Environment().addClientLoader(LocalResourceLoader)

  val document =
    try {
      Raml10Parser(environment).parseFileAsync(uri.toString()).get() as Document
    } catch (x: ExecutionException) {
      throw x.cause!!
    }

  val validatedDocument = document.cloneUnit() as Document
  val validationReport = AMF.validate(validatedDocument, ProfileNames.RAML10(), MessageStyles.RAML()).get()

  return ProcessResult(document, validatedDocument, validationReport)
}
```

**Comment by arielmirra** [comment]
Hi @kdubb! I've been looking into this and have some clarifications and a solution. 

Parsing an overlay does not give you the resolved, merged, complete API you're looking for. For that, you must  `resolve` the overlay with a `Raml10Resolver`. That gives you the complete model you want. 

I've tested this and pushed an example in [this commit](https://github.com/aml-org/examples/commit/750c326e94bc84993a8fdc12e7071e329212bd26) with the test files you provided (thanks!) to the examples repository.

Also excerpted for history's sake:

```java
@Test
public void resolveRamlOverlay() throws ExecutionException, InterruptedException {
    final Raml10Parser parser = new Raml10Parser();
    final Raml10Resolver resolver = new Raml10Resolver();

    final Document unresolvedModel = (Document) parser.parseFileAsync("file://resources/examples/raml-overlay/test-overlay.raml").get();
    assertThat("unresolved overlay should reference main API", unresolvedModel.references().size() == 1);

    final Document resolvedModel = (Document) resolver.resolve(unresolvedModel, ResolutionPipeline.EDITING_PIPELINE());
    assertThat("resolved model shouldn't reference anything", resolvedModel.references().size() == 0);

    System.out.println(new Raml10Renderer().generateString(resolvedModel).get());
}
```

Note that I've used `ResolutionPipeline.EDITING_PIPELINE()` to keep all declarations in the API, but only passing the overlay resolves it just fine. The difference is that the editing pipeline has these 3 lines that the default pipeline does not add:

```raml
mediaType: application/json
annotationTypes:
  test-ann:
    type: boolean
```

I hope I made myself clear enough. It's a mixture of things so I've made a test in case you want to run/debug and have it for future reference. I'm closing this issue but you can ask or raise another one if anything comes up. Thanks!

**Comment by kdubb** [comment]
@arielmirra Thank you!  This was very helpful.

Side note, is there documentation of the different pipelines?

**Comment by arielmirra** [comment]
@kdubb today we updated the documentation with new docs. This should be helpful: https://a.ml/docs/AMF/Using%20AMF/amf_resolution

**Comment by kdubb** [comment]
@arielmirra 🎉🎉🎉

One final off topic question.... Would it be possible to open up the "Discussions" feature for this project?

We've built a large generation codebase on the AMF client and given that the documentation is just coming around, I'm quite sure we're doing a lot of things wrong.  It would be nice to have a place to ask questions about intended usage without creating issues each time.

**Comment by arielmirra** [comment]
@kdubb I think it's opened, check if you can access this link: https://github.com/aml-org/amf/discussions 

For some reason, the "discussions" tab is not shown, probably because it's still in beta.

**Comment by kdubb** [comment]
@arielmirra It is opened and the tab is showing for me!
